begin;
set local role authenticated;
do $$
declare eid integer; r public.tbl_events; allowed boolean; checks integer:=0; count_before integer;
begin
 perform set_config('request.jwt.claim.sub','3eaa15aa-2a8e-49b3-ae37-aef126239680',true);
 select count(*) into count_before from public.tbl_events where created_by=35;
 eid:=public.create_activity(jsonb_build_object('title','[QA] Phase 2 transactional check','description','Rolled back after all assertions.','category','Education','join_type','direct','location','Bengaluru','latitude',12.97,'longitude',77.59,'location_instruction','Main entrance','verified_only',true,'age_min',20,'age_max',45,'gender_preference','male','max_participants',null,'event_start_time',null),'published');
 select * into r from public.tbl_events where id=eid;
 assert r.id=eid and r.created_by=35; checks:=checks+1;
 assert r.max_participants is null and r.event_start_time is null and r.event_end_time is null and r.registration_close_time is null; checks:=checks+1;
 assert r.verified_only and r.age_min=20 and r.age_max=45 and r.gender_preference='male' and r.location_instruction='Main entrance'; checks:=checks+1;
 assert r.latitude=12.97 and r.longitude=77.59 and r.join_type='direct'; checks:=checks+1;
 begin perform public.update_activity(eid,'{"age_min":50,"age_max":20}'); raise exception 'Invalid age accepted'; exception when sqlstate '22023' then checks:=checks+1; end;
 begin perform public.update_activity(eid,'{"max_participants":0}'); raise exception 'Zero capacity accepted'; exception when sqlstate '22023' then checks:=checks+1; end;
 begin perform public.update_activity(eid,'{"event_start_time":"2030-01-02T10:00:00Z","event_end_time":"2030-01-02T09:00:00Z"}'); raise exception 'Reversed schedule accepted'; exception when sqlstate '22023' then checks:=checks+1; end;
 begin perform public.update_activity(eid,'{"gender_preference":"invented"}'); raise exception 'Invalid gender accepted'; exception when sqlstate '22023' then checks:=checks+1; end;
 perform set_config('request.jwt.claim.sub','f034763a-7b42-4e58-8fee-8ba4f3bdd59b',true);
 begin perform public.request_join_activity(eid); raise exception 'Unverified user admitted'; exception when insufficient_privilege then checks:=checks+1; end;
 begin perform public.update_activity(eid,'{"title":"Not mine"}'); raise exception 'Nonowner changed event'; exception when insufficient_privilege then checks:=checks+1; end;
 perform set_config('request.jwt.claim.sub','3eaa15aa-2a8e-49b3-ae37-aef126239680',true);
 perform public.update_activity(eid,'{"verified_only":false,"age_min":null,"age_max":null,"gender_preference":null,"max_participants":100,"join_type":"approval","location_instruction":"Room 404"}');
 select * into r from public.tbl_events where id=eid;
 assert not r.verified_only and r.age_min is null and r.age_max is null and r.gender_preference is null and r.max_participants=100 and r.join_type='approval' and r.location_instruction='Room 404'; checks:=checks+1;
 perform set_config('request.jwt.claim.sub','f034763a-7b42-4e58-8fee-8ba4f3bdd59b',true);
 perform public.request_join_activity(eid);
 assert exists(select 1 from public.tbl_event_participants where event_id=eid and user_id=44 and status='pending'); checks:=checks+1;
 perform public.request_join_activity(eid,'left');
 assert exists(select 1 from public.tbl_event_participants where event_id=eid and user_id=44 and status='left'); checks:=checks+1;
 perform set_config('request.jwt.claim.sub','3eaa15aa-2a8e-49b3-ae37-aef126239680',true);
 begin perform public.update_activity(eid,'{"is_paid":true,"price_inr":10}'); raise exception 'Individual paid hosting allowed'; exception when insufficient_privilege then checks:=checks+1; end;
 perform public.update_activity(eid,'{"visibility_type":"squad","age_min":15}');
 perform set_config('request.jwt.claim.sub','96fe1862-ef25-489a-a5c5-ad045ce66311',true);
 -- Only explicit existing friendships grant the Squad audience.
 select exists(select 1 from public.tbl_events where id=eid) into allowed;
 assert allowed=private.activity_squad_visible(eid); checks:=checks+1;
 perform set_config('request.jwt.claim.sub','3eaa15aa-2a8e-49b3-ae37-aef126239680',true);
 perform public.update_activity(eid,'{"visibility_type":"public"}');
 perform set_config('request.jwt.claim.sub','96fe1862-ef25-489a-a5c5-ad045ce66311',true);
 begin perform public.request_join_activity(eid); raise exception 'Missing DOB admitted to age restriction'; exception when insufficient_privilege then checks:=checks+1; end;
 assert public.check_onboarding_username('phase2_available_candidate')=true; checks:=checks+1;
 assert public.check_onboarding_username('suchit_paradhan')=false; checks:=checks+1;
 begin perform public.complete_my_onboarding('3eaa15aa-2a8e-49b3-ae37-aef126239680','QA','phase2_available_candidate',null,null); raise exception 'Identity substitution accepted'; exception when insufficient_privilege then checks:=checks+1; end;
 perform public.complete_my_onboarding('96fe1862-ef25-489a-a5c5-ad045ce66311','Priya Nair','phase2_available_candidate',null,null);
 assert public.check_onboarding_username('phase2_available_candidate')=true; checks:=checks+1;
 raise notice 'Phase 2 checks passed: %',checks;
end $$;
reset role;
select 'PASS: 20 activity/onboarding assertions; all writes rolled back' as result;
rollback;
