import React, { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, Share, Switch, Text, View } from 'react-native';
import { supabase } from '../../lib/supabase';
import { communitiesProductionService, manageCommunity, type CommunityDetail } from '../../services/communities-production';
import { realtimeChatService, type ChatMember } from '../../services/realtime-chat';
import { CreateCommunitySheet } from './reference-community';
import { Action, Button, ErrorLine, Header, Icon, Page, SearchField, Sheet, Skeleton, ui, usePalette, purple } from '../reconstruction/ui';
export function CommunityInfo({ id, back, openProfile, openChat, openPosts, onChanged, onDeleted }: { id: string; back: () => void; openProfile: (id: string) => void; openChat: () => void; openPosts: () => void; onChanged: (c: CommunityDetail) => void; onDeleted: () => void }) {
 const c = usePalette();
 const [community, setCommunity] = useState<CommunityDetail | null>(null), [members, setMembers] = useState<ChatMember[]>([]), [query, setQuery] = useState('');
 const [view, setView] = useState<'info' | 'settings' | 'requests'>('info'), [edit, setEdit] = useState(false), [confirm, setConfirm] = useState<'leave' | 'delete' | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState('');
 const [requests, setRequests] = useState<{ user_id: number; name: string }[]>([]), [requestsLoading, setRequestsLoading] = useState(false);
 const refresh = async () => { const result = await communitiesProductionService.getCommunity(id); setCommunity(result); onChanged(result); if (result.membership === 'created' || result.membership === 'joined') setMembers(await realtimeChatService.loadConversationMembers(Number(id))); };
 useEffect(() => { void refresh().catch(e => setError(e.message)); }, [id]);
 const admin = community?.membershipRole === 'admin', joined = community?.membership === 'created' || community?.membership === 'joined';
 const preference = async (key: string, value: boolean) => { setBusy(true); setError(''); try { await manageCommunity(id, 'preferences', { [key]: value }); await refresh(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
 const loadRequests = async () => { setRequestsLoading(true); setError(''); try { const { data, error } = await supabase.from('tbl_community_join_requests').select('user_id,tbl_users(username,fullname)').eq('room_id', Number(id)).eq('status', 'pending').limit(50); if (error) throw error; setRequests((data || []).map((r: any) => ({ user_id: r.user_id, name: r.tbl_users?.fullname || r.tbl_users?.username || `Member ${r.user_id}` }))); } catch (e: any) { setError(e.message); } finally { setRequestsLoading(false); } };
 const respond = async (user: number, action: 'approve' | 'reject') => { setBusy(true); try { await manageCommunity(id, action, { user_id: user }); await loadRequests(); await refresh(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } };
 const field = (title: string, subtitle: string, value: boolean, key: string) => <View style={[ui.row, { minHeight: 79, borderBottomWidth: 1, borderColor: c.border }]}><View style={{ flex: 1, gap: 8 }}><Text style={{ color: c.text, fontSize: 13 }}>{title}</Text><Text style={{ color: c.muted, fontSize: 12 }}>{subtitle}</Text></View><Switch accessibilityLabel={title} disabled={busy} value={value} onValueChange={v => void preference(key, v)} trackColor={{ true: purple, false: '#616775' }} /></View>;
 return <Page><Header title={view === 'info' ? 'Community Info' : view === 'settings' ? 'Settings' : 'Join Requests'} back={view === 'info' ? back : () => setView(view === 'requests' ? 'settings' : 'info')}>
 {view === 'info' && <><Action name="share-social-outline" label="Share community" onPress={() => { if (community) void Share.share({ message: `Join our community "${community.name}" on WeNitro! Tap here: wenitro://community/join/${id}` }).catch(e => setError(e.message)); }} />{admin && <Action name="settings-outline" label="Community settings" onPress={() => setView('settings')} />}</>}
 </Header><ErrorLine text={error} />{!community ? <Skeleton /> : <ScrollView contentContainerStyle={{ padding: 17, gap: 14, paddingBottom: 36 }}>
 {view === 'info' ? <>
 <View style={{ alignItems: 'center', paddingVertical: 10, gap: 14 }}>{community.imageUrl ? <Image source={{ uri: community.imageUrl }} style={{ width: 88, height: 88, borderRadius: 44 }} /> : <View style={{ width: 88, height: 88, borderRadius: 44, backgroundColor: c.card, alignItems: 'center', justifyContent: 'center' }}><Icon name="people" size={35} color={purple} /></View>}<Text style={{ color: c.text, fontSize: 20, fontWeight: '600' }}>{community.name}</Text></View>
 <View style={{ backgroundColor: c.card, borderRadius: 12, padding: 17, gap: 10 }}><Text style={{ color: c.muted, fontSize: 12 }}>Category</Text><Text style={{ color: c.text, fontSize: 13 }}>{community.category}</Text><Text style={{ color: c.muted, fontSize: 12, marginTop: 8 }}>Description</Text><Text style={{ color: c.text, fontSize: 13, lineHeight: 20 }}>{community.description}</Text></View>
 {!joined ? <Button label={community.membership === 'pending' ? 'Join request pending' : community.requiresApproval ? 'Request to join' : 'Join Community'} disabled={community.membership === 'pending'} busy={busy} onPress={() => { setBusy(true); void communitiesProductionService.join(id).then(refresh).catch(e => setError(e.message)).finally(() => setBusy(false)); }} /> : <View style={{ flexDirection: 'row', gap: 12 }}><Pressable accessibilityRole="button" onPress={openChat}><Text style={{ color: '#9387FF', padding: 10 }}>Open conversation</Text></Pressable><Pressable accessibilityRole="button" onPress={openPosts}><Text style={{ color: '#9387FF', padding: 10 }}>Community posts</Text></Pressable></View>}
 <Text style={{ color: c.text, fontSize: 16, fontWeight: '600', marginTop: 12 }}>Members ({community.memberCount ?? members.length})</Text>
 {joined ? <><SearchField accessibilityLabel="Search members" placeholder="Search members..." value={query} onChangeText={setQuery} style={{ margin: 0 }} />{members.filter(m => `${m.profiles?.full_name} ${m.profiles?.username}`.toLowerCase().includes(query.toLowerCase())).map(m => <Pressable accessibilityRole="button" key={m.user_id} onPress={() => openProfile(String(m.user_id))} style={[ui.row, { paddingHorizontal: 0 }]}>{m.profiles?.avatar_url ? <Image source={{ uri: m.profiles.avatar_url }} style={ui.avatar} /> : <Icon name="person-circle-outline" size={46} color={c.muted} />}<View style={{ flex: 1, gap: 5 }}><Text style={{ color: c.text, fontWeight: '600', fontSize: 13 }}>{m.profiles?.full_name || m.profiles?.username || 'Member'}</Text><Text style={{ color: c.muted, fontSize: 11 }}>@{m.profiles?.username || 'member'}</Text></View>{String(m.user_id) === community.ownerId && <Text style={{ color: '#9B8FFF', fontSize: 11 }}>Creator</Text>}</Pressable>)}</> : <Text style={{ color: c.muted, fontSize: 12 }}>Join to see community members.</Text>}
 {community.membership === 'joined' && <Pressable accessibilityRole="button" onPress={() => setConfirm('leave')} style={{ marginTop: 24, borderWidth: 1, borderColor: '#E65E6D', borderRadius: 10, padding: 14, alignItems: 'center' }}><Text style={{ color: '#D9495B', fontSize: 13, fontWeight: '600' }}>Leave Community</Text></Pressable>}
 </> : view === 'settings' ? <>
 <Text style={[ui.section, { color: c.text, marginTop: 4, fontWeight: '600' }]}>INFORMATION</Text><Pressable accessibilityRole="button" onPress={() => setEdit(true)} style={[ui.row, { backgroundColor: c.card, borderRadius: 12, minHeight: 85, borderColor: c.border, borderWidth: 1 }]}><View style={{ flex: 1, gap: 10 }}><Text style={{ color: c.text, fontSize: 13 }}>Edit Community Profile</Text><Text style={{ color: c.muted, fontSize: 11 }}>Update name, description, avatar, category</Text></View><Icon name="create-outline" color={purple} /></Pressable>
 <Text style={[ui.section, { color: c.text, fontWeight: '600' }]}>PREFERENCES</Text><View style={{ backgroundColor: c.card, borderRadius: 12, borderWidth: 1, borderColor: c.border, overflow: 'hidden' }}>{field('Verified Only Check', 'Only blue ticks can join', community.verifiedOnly, 'verified_only')}{field('Requires Admin Approval', 'Requests go to list', community.requiresApproval, 'requires_approval')}{community.requiresApproval && <Pressable accessibilityRole="button" onPress={() => { setView('requests'); void loadRequests(); }} style={{ padding: 15 }}><Text style={{ color: '#9A8DFF', fontSize: 12 }}>View Pending Join Requests</Text></Pressable>}{field('Only Admins can post', 'Announcements mode', community.adminsOnly, 'admins_only')}</View>
 <Pressable accessibilityRole="button" onPress={() => setConfirm('delete')} style={{ marginTop: 30, borderWidth: 1, borderColor: '#E65E6D', borderRadius: 10, padding: 14, alignItems: 'center' }}><Text style={{ color: '#F17481', fontSize: 13 }}>Delete Community</Text></Pressable>
 </> : requestsLoading ? <Skeleton count={2} /> : requests.length ? requests.map(r => <View key={r.user_id} style={{ gap: 10, padding: 14, backgroundColor: c.card, borderRadius: 12 }}><Text style={{ color: c.text }}>{r.name}</Text><Button label="Approve" disabled={busy} onPress={() => void respond(r.user_id, 'approve')} /><Button label="Reject" danger disabled={busy} onPress={() => void respond(r.user_id, 'reject')} /></View>) : <Text style={{ color: c.muted, textAlign: 'center', marginTop: 40, fontSize: 13 }}>No pending join requests</Text>}
 </ScrollView>}
 {edit && community && <CreateCommunitySheet initial={community} onClose={() => setEdit(false)} onCreated={() => { setEdit(false); void refresh().catch(e => setError(e.message)); }} />}
 {confirm && <Sheet title={confirm === 'leave' ? "Leave Community?" : "Delete Community?"} centered close={() => { if (!busy) setConfirm(null); }}><Text style={{ color: c.muted, lineHeight: 21, fontSize: 13 }}>{confirm === 'leave' ? `You will leave ${community?.name || 'this community'} and it will be removed from your community conversations.` : 'This permanently deletes this community, its conversation, polls and posts. This action cannot be undone.'}</Text><Button label="Cancel" disabled={busy} onPress={() => setConfirm(null)} /><Button label={confirm === 'leave' ? "Leave Community" : "Delete"} danger busy={busy} onPress={() => { setBusy(true); const task = confirm === 'leave' ? communitiesProductionService.leave(id) : manageCommunity(id, 'delete', { confirmed: true }); void task.then(onDeleted).catch(e => { setError(e.message); setConfirm(null); }).finally(() => setBusy(false)); }} /></Sheet>}
 </Page>;
}
