import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import type { AppData } from '../../../App';
import { profileProductionService, type ContentListItem } from '../../services/profile-production';
import { activitiesProductionService } from '../../services/activities-production';
import { loadActivityParticipantCounts } from '../../services/wenitro';
import { prepareReferenceActivities } from './feed-search';
import { Button, ErrorLine, Header, Icon, Page, Skeleton, ui, usePalette, purple } from './ui';
export function ReferenceCollection({ kind, data, setData, back, openActivity, openVibe }: { kind: 'saved' | 'liked'; data: AppData; setData: React.Dispatch<React.SetStateAction<AppData>>; back: () => void; openActivity: (id: string) => void; openVibe: (id: string) => void }) {
 const c = usePalette(); const [items, setItems] = useState<ContentListItem[]>([]), [cursor, setCursor] = useState<string | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState('');
 const load = async (more = false) => { setLoading(true); setError(''); try { const page = await (kind === 'saved' ? profileProductionService.listSaved : profileProductionService.listLiked)({ limit: 25, before: more ? cursor || undefined : undefined }); setItems(current => more ? [...current, ...page.items] : page.items); setCursor(page.nextCursor); } catch (e: any) { setError(e.message); } finally { setLoading(false); } };
 useEffect(() => { void load(); }, [kind, data.userId]);
 const open = async (id: string) => { try { if (!data.activities.some(a => a.id === id)) { const { activity, viewerState } = await activitiesProductionService.getDetails(id); const [prepared] = await prepareReferenceActivities([{ ...activity, viewerState }]); setData(current => current.userId !== data.userId ? current : ({ ...current, activities: [...current.activities, prepared] })); } openActivity(id); } catch (e: any) { setError(e.message); } };
 const vibes = data.vibes.filter(v => (kind === 'saved' ? data.savedIds : data.likedIds).includes('vibe:' + v.id));
 return <Page><Header title={kind === 'saved' ? 'My Saved Items' : 'Liked Activities'} back={back} /><ErrorLine text={error} />{loading && !items.length ? <Skeleton /> : <ScrollView contentContainerStyle={{ padding: 17 }}>{items.map(item => <Pressable accessibilityRole="button" key={item.id} onPress={() => void open(String(item.content.id))} style={[ui.row, { paddingHorizontal: 0, borderBottomWidth: 1, borderColor: c.border }]}><Icon name="calendar-outline" color={purple} /><View style={{ flex: 1, gap: 6 }}><Text style={{ color: c.text, fontSize: 13 }}>{String(item.content.title)}</Text><Text style={{ color: c.muted, fontSize: 11 }}>{String(item.content.display_location || item.content.location || '')}</Text></View><Icon name="chevron-forward" color={c.muted} size={17} /></Pressable>)}{vibes.map(v => <Pressable accessibilityRole="button" key={v.id} onPress={() => openVibe(v.id)} style={ui.row}><Icon name="film-outline" color={purple} /><Text style={{ color: c.text, fontSize: 13 }}>{v.text || 'Vibe'}</Text></Pressable>)}{!items.length && !vibes.length && <View style={{ alignItems: 'center', paddingVertical: 95, paddingHorizontal: 18, gap: 15 }}><Icon name={kind === 'liked' ? 'heart-outline' : 'bookmark-outline'} color={c.muted} size={55} /><Text style={{ color: c.text, fontWeight: '600', fontSize: 17 }}>{kind === 'liked' ? 'No liked items yet' : 'No saved items yet'}</Text><Text style={{ color: c.muted, fontSize: 12, textAlign: 'center' }}>{kind === 'liked' ? 'Activities you like will show up here.' : 'Items you save will show up here.'}</Text></View>}{cursor && <Button label="Load more" busy={loading} onPress={() => void load(true)} />}</ScrollView>}</Page>;
}
