import { Asset } from 'expo-asset';
import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Image, Platform, Pressable, ScrollView, Switch, Text, View } from 'react-native';
import type { Activity, AppData, Screen } from '../../../App';
import { activitiesProductionService, type ActivityListItem } from '../../services/activities-production';
import { communitiesProductionService, type CommunitySummary } from '../../services/communities-production';
import { activityService, loadActivityParticipantCounts } from '../../services/wenitro';
import { supabase } from '../../lib/supabase';
import { activityLocationService } from '../../services/activity-location';
import { INTEREST_CATEGORIES } from '../../domain/interest-categories';
import { Action, Button, ErrorLine, Header, Icon, Page, Pills, SearchField, Sheet, Skeleton, ui, usePalette, purple } from './ui';
function activityState(a: Activity) {
  const ended = a.status === 'completed' || Boolean(a.endsAt && Date.parse(a.endsAt) <= Date.now());
  if (ended) return 'Completed';
  if (a.registrationClosesAt && Date.parse(a.registrationClosesAt) <= Date.now()) return 'Registration Closed';
  return 'Upcoming';
}

function activityTime(value?: string) {
  if (!value) return 'To Be Decided';
  return new Date(value).toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
}

function ActivityFeedSkeleton() {
  const c = usePalette();
  return <View accessibilityLabel="Loading activities" style={{ gap: 15 }}>{[0, 1].map(index => <View key={index} style={{ backgroundColor: c.card, borderRadius: 18, overflow: 'hidden' }}><View style={{ height: 194, backgroundColor: c.inset }} /><View style={{ padding: 13, gap: 11 }}><View style={{ width: '72%', height: 15, borderRadius: 5, backgroundColor: c.inset }} /><View style={{ width: '35%', height: 34, borderRadius: 7, backgroundColor: c.inset }} /><View style={{ width: '100%', height: 34, borderRadius: 7, backgroundColor: c.inset }} /><View style={{ width: '58%', height: 25, borderRadius: 13, backgroundColor: c.inset }} /></View></View>)}</View>;
}

export function ReferenceActivityCard({ activity: a, liked, onLike, onShowLikers, open }: { activity: Activity; liked: boolean; onLike: () => void; onShowLikers: () => void; open: () => void }) {
  const c = usePalette(); const state = activityState(a);
  const joined = ['approved', 'going', 'paid'].includes(String(a.viewerStatus));
  return <View style={{ backgroundColor: c.card, borderRadius: 18, overflow: 'hidden', marginBottom: 15, borderWidth: 1, borderColor: c.border }}>
    <Pressable accessibilityRole="button" accessibilityLabel={`Open activity ${a.title}`} onPress={open}>
      <Image source={typeof a.image === 'string' ? { uri: a.image } : a.image} style={{ width: '100%', height: 194, backgroundColor: c.inset }} resizeMode="cover" />
      <View style={{ position: 'absolute', left: 10, bottom: 10, flexDirection: 'row', gap: 6 }}>{joined && <View style={{ backgroundColor: '#12B886', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 5 }}><Text style={{ color: '#FFF', fontSize: 9, fontWeight: '700' }}>Joined</Text></View>}<View style={{ backgroundColor: '#FFF', paddingHorizontal: 9, paddingVertical: 6, borderRadius: 5 }}><Text style={{ color: '#1A202C', fontSize: 9, fontWeight: '700' }}>◷ {state}</Text></View></View>
      <View style={{ position: 'absolute', right: 9, top: 8, width: 31, height: 31, borderRadius: 16, backgroundColor: '#111827B8', alignItems: 'center', justifyContent: 'center' }}><Icon name="ellipsis-vertical" size={17} color="#FFF" /></View>
    </Pressable>
    <View style={{ padding: 13, gap: 10 }}>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><Pressable accessibilityRole="button" onPress={open} style={{ flex: 1 }}><Text style={{ color: c.text, fontSize: 15, fontWeight: '700' }} numberOfLines={2}>{a.title}</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel={liked ? `Unlike ${a.title}` : `Like ${a.title}`} accessibilityHint="Long-Press to see who liked" onPress={onLike} onLongPress={onShowLikers} delayLongPress={450} style={{ minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' }}><Icon name={liked ? 'heart' : 'heart-outline'} color={liked ? '#F3285F' : c.muted} size={21} /><Text style={{ color: c.muted, fontSize: 9 }}>{a.likeCount || 0}</Text></Pressable></View>
      <View style={{ alignSelf: 'flex-start', borderWidth: 1, borderColor: c.border, borderRadius: 7, padding: 9, flexDirection: 'row', gap: 6 }}><Icon name="calendar-outline" size={12} color={purple} /><Text style={{ fontSize: 10, color: c.text }}>{activityTime(a.startsAt)}</Text></View>
      <View style={{ borderWidth: 1, borderColor: c.border, borderRadius: 7, padding: 9, flexDirection: 'row', gap: 6 }}><Icon name="location-outline" size={12} color="#C95781" /><Text style={{ fontSize: 10, color: c.text, flex: 1 }} numberOfLines={1}>{a.where || 'Location to be decided'}</Text></View>
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 7 }}>{a.hostAvatar ? <Image source={{ uri: a.hostAvatar }} style={{ width: 29, height: 29, borderRadius: 15 }} /> : <Icon name="person-circle-outline" color={c.muted} size={29} />}<Text style={{ color: c.muted, fontSize: 11, flex: 1 }}>@{a.host || 'host'}</Text><Icon name={a.visibility === 'public' ? 'globe-outline' : 'lock-closed-outline'} color={c.muted} size={14} /><Icon name="people-outline" color={c.muted} size={17} /><Text style={{ color: c.muted, fontSize: 10 }}>{a.joined}</Text></View>
    </View>
  </View>;
}

export function ReferenceFeed({ data, setData, go, openActivity, refreshOnMount = true }: { data: AppData; setData: React.Dispatch<React.SetStateAction<AppData>>; go: (s: Screen) => void; openActivity: (id: string) => void; refreshOnMount?: boolean }) {
  const c = usePalette();
  const [filter, setFilter] = useState('All');
  const [categories, setCategories] = useState<string[]>([]);
  const [draftCategories, setDraftCategories] = useState<string[]>([]);
  const [filterOpen, setFilterOpen] = useState(false);
  const [dateFrom, setDateFrom] = useState('');
  const [dateTo, setDateTo] = useState('');
  const [price, setPrice] = useState('All');
  const [gender, setGender] = useState('All');
  const [verifiedOnly, setVerifiedOnly] = useState(false);
  const [draft, setDraft] = useState({ dateFrom: '', dateTo: '', price: 'All', gender: 'All', verifiedOnly: false });
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(data.activities.length === 0);
  const [nearby, setNearby] = useState<{ latitude: number; longitude: number } | null>(null);
  const [locating, setLocating] = useState(false);

  useEffect(() => { if (!refreshOnMount) { setLoading(false); return; } const controller = new AbortController(); let active = true; setLoading(true); void activitiesProductionService.discover({ pageSize: 50, upcomingOnly: false, sort: 'newest', signal: controller.signal }).then(async page => { const prepared = await prepareReferenceActivities(page.items); if (active) setData(current => ({ ...current, activities: prepared })); }).catch(e => { if (active && !controller.signal.aborted) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; controller.abort(); }; }, [refreshOnMount]);
  const chooseFilter = async (value: string) => { setFilter(value); if (value !== 'Nearby' || nearby || locating) return; setLocating(true); setError(''); try { setNearby(await activityLocationService.current()); } catch (e: any) { setError(e.message); } finally { setLocating(false); } };
  const activities = useMemo(() => { let list = data.activities.filter(a => a.status !== 'draft' && a.status !== 'cancelled'); if (categories.length) list = list.filter(a => categories.includes(a.category)); if (dateFrom) list = list.filter(a => a.startsAt && Date.parse(a.startsAt) >= Date.parse(`${dateFrom}T00:00:00`)); if (dateTo) list = list.filter(a => a.startsAt && Date.parse(a.startsAt) <= Date.parse(`${dateTo}T23:59:59`)); if (price === 'Free') list = list.filter(a => a.price === 'Free' || Number(a.price.replace(/[^0-9.]/g, '')) === 0); if (price === 'Paid') list = list.filter(a => a.price !== 'Free' && Number(a.price.replace(/[^0-9.]/g, '')) > 0); if (gender !== 'All') { const wanted = gender === 'Non-binary' ? 'non_binary' : gender.toLowerCase(); list = list.filter(a => String(a.genderPreference || '').toLowerCase() === wanted); } if (verifiedOnly) list = list.filter(a => a.verifiedOnly); if (filter === 'Trending') list = [...list].sort((a, b) => (b.likeCount || 0) + b.joined - ((a.likeCount || 0) + a.joined)); if (filter === 'Nearby') list = nearby ? list.filter(a => a.latitude != null && a.longitude != null && distanceKm(nearby.latitude, nearby.longitude, a.latitude, a.longitude) <= 25) : []; if (filter === 'Today' || filter === 'Tomorrow') { const day = new Date(); if (filter === 'Tomorrow') day.setDate(day.getDate() + 1); list = list.filter(a => a.startsAt && new Date(a.startsAt).toDateString() === day.toDateString()); } return list; }, [data.activities, nearby, filter, categories, dateFrom, dateTo, price, gender, verifiedOnly]);
  const like = async (a: Activity) => { const key = 'activity:' + a.id, liked = data.likedIds.includes(key); try { await activityService.setLiked(a.id, !liked); setData(current => ({ ...current, likedIds: liked ? current.likedIds.filter(id => id !== key) : [...current.likedIds, key], activities: current.activities.map(item => item.id === a.id ? { ...item, likeCount: Math.max(0, (item.likeCount || 0) + (liked ? -1 : 1)) } : item) })); } catch (e: any) { setError(e.message); } };
  const showLikers = async (a: Activity) => { try { const likers = await activityService.listLikers(a.id); Alert.alert(likers.length ? `Liked by ${likers.length}` : 'No likes yet', likers.length ? likers.map(item => item.name).join('\n') : 'Be the first to like this Activity.'); } catch (e: any) { setError(e.message); } };
  const joinCommunity = async (id: string) => { try { await communitiesProductionService.setMembership(id, true); setData(current => ({ ...current, communities: current.communities.map(room => room.id === id ? { ...room, membership: 'joined', memberCount: room.memberCount + 1 } : room) })); } catch (e: any) { setError(e.message); } };
  const communityCards = data.communities.filter(room => room.membership !== 'created').slice(0, 8);
  const renderActivity = (a: Activity) => <ReferenceActivityCard key={a.id} activity={a} liked={data.likedIds.includes('activity:' + a.id)} onLike={() => void like(a)} onShowLikers={() => void showLikers(a)} open={() => openActivity(a.id)} />;
  return <Page>
    <View style={{ height: 62, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 8 }}><Image source={require('../../../assets/wenitro-logo-transparent.png')} style={{ width: 29, height: 29 }} /><Text style={{ color: c.text, fontSize: 20, fontWeight: '800', flex: 1 }}>WeNitro</Text><Action name="search-outline" label="Search" onPress={() => go('search')} /><Action name="notifications-outline" label="Notifications" onPress={() => go('notifications')} /></View>
    <ScrollView contentContainerStyle={{ paddingHorizontal: 14, paddingBottom: 24 }}>
      <Pressable accessibilityRole="button" onPress={() => go('shop')} style={{ borderWidth: 1, borderColor: '#6455A650', backgroundColor: data.nitro >= 500 ? '#6657EC' : '#4B369B22', borderRadius: 17, padding: 17, minHeight: 119, justifyContent: 'center', flexDirection: 'row', alignItems: 'center', gap: 12 }}><Icon name={data.nitro >= 500 ? 'gift-outline' : 'lock-closed-outline'} color={data.nitro >= 500 ? '#FFF' : '#CEB94A'} size={25} /><View style={{ flex: 1, gap: 10 }}><Text style={{ color: data.nitro >= 500 ? '#FFF' : '#D7C849', fontSize: 10, fontWeight: '700', letterSpacing: .6 }}>{data.nitro >= 500 ? 'NITRO STORE' : 'LOCKED · NITRO STORE'}</Text><Text style={{ color: data.nitro >= 500 ? '#EEE9FF' : c.text, fontSize: 11 }}>You have {data.nitro} pts. {data.nitro < 500 ? `Earn ${500 - data.nitro} more to unlock.` : 'Shop rewards with your points.'}</Text></View><Icon name="gift-outline" size={39} color={data.nitro >= 500 ? '#FFFFFF88' : '#837C9A55'} /></Pressable>
      <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginVertical: 13 }} contentContainerStyle={{ gap: 8 }}>{[['All', null], ['Trending', 'flame-outline'], ['Nearby', 'location-outline'], ['Today', 'time-outline'], ['Tomorrow', 'calendar-outline']].map(([label, icon]) => <Pressable accessibilityRole="button" accessibilityState={{ selected: filter === label }} onPress={() => void chooseFilter(label!)} key={label} style={{ paddingHorizontal: 14, paddingVertical: 11, borderRadius: 10, backgroundColor: filter === label ? purple : c.card, flexDirection: 'row', gap: 7 }}>{icon && <Icon name={icon as any} size={14} color={filter === label ? 'white' : '#9A83DA'} />}<Text style={{ color: filter === label ? 'white' : c.muted, fontSize: 13 }}>{label}</Text></Pressable>)}</ScrollView>
      <View style={{ flexDirection: 'row', alignItems: 'center', marginBottom: 10 }}><Icon name="flame" size={17} color="#F14571" /><Text style={{ color: c.text, fontWeight: '700', fontSize: 17, flex: 1, marginLeft: 8 }}>Activity for You</Text><Pressable accessibilityRole="button" onPress={() => { setDraftCategories(categories); setDraft({ dateFrom, dateTo, price, gender, verifiedOnly }); setFilterOpen(true); }} style={{ backgroundColor: c.card, borderRadius: 20, flexDirection: 'row', gap: 5, padding: 9 }}><Icon name="filter-outline" size={18} /><Text style={{ color: c.text, fontSize: 11 }}>Filter{categories.length || dateFrom || dateTo || price !== 'All' || gender !== 'All' || verifiedOnly ? ' •' : ''}</Text></Pressable></View>
      <ErrorLine text={error} />
      {loading ? <ActivityFeedSkeleton /> : <>{activities.slice(0, 2).map(renderActivity)}{communityCards.length > 0 && <View style={{ marginHorizontal: -14, paddingVertical: 8, marginBottom: 15 }}><View style={{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, marginBottom: 10 }}><Text style={{ color: c.text, fontSize: 17, fontWeight: '700', flex: 1 }}>Communities for You</Text><Pressable accessibilityRole="button" onPress={() => go('communities')}><Text style={{ color: '#9D8AFF', fontSize: 12 }}>Explore ›</Text></Pressable></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ paddingHorizontal: 14, gap: 10 }}>{communityCards.map(room => <View key={room.id} style={{ width: 184, minHeight: 164, backgroundColor: c.card, borderRadius: 15, overflow: 'hidden', borderWidth: 1, borderColor: c.border }}>
          <Pressable accessibilityRole="button" accessibilityLabel={`Open community ${room.name}`} onPress={() => go('communities')}>
           {room.image ? <Image source={{ uri: room.image }} style={{ height: 77, width: '100%' }} /> : <View style={{ height: 77, backgroundColor: c.inset, alignItems: 'center', justifyContent: 'center' }}><Icon name="people" color="#8F7EFF" size={28} /></View>}
           <View style={{ paddingHorizontal: 10, paddingTop: 10, gap: 5 }}><Text style={{ color: '#9D8AFF', fontSize: 9, textTransform: 'uppercase' }}>{room.category}</Text><Text style={{ color: c.text, fontSize: 13, fontWeight: '700' }} numberOfLines={1}>{room.name}</Text></View>
          </Pressable>
          <View style={{ paddingHorizontal: 10, paddingBottom: 10, paddingTop: 5, flexDirection: 'row', alignItems: 'center' }}><Text style={{ color: c.muted, fontSize: 10, flex: 1 }}>{room.memberCount} members</Text>{room.membership === 'joined' ? <Text style={{ color: '#65D79A', fontSize: 10 }}>Joined</Text> : <Pressable accessibilityRole="button" accessibilityLabel={`Join ${room.name}`} onPress={() => void joinCommunity(room.id)} style={{ backgroundColor: purple, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6 }}><Text style={{ color: '#FFF', fontSize: 10, fontWeight: '700' }}>Join</Text></Pressable>}</View>
         </View>)}</ScrollView></View>}{activities.slice(2).map(renderActivity)}{!activities.length && <Text style={{ color: c.muted, fontSize: 13, padding: 25, textAlign: 'center' }}>{filter === 'Nearby' && !nearby ? locating ? 'Finding your location...' : 'Location access is needed for Nearby. Tap Nearby to retry.' : 'No activities match these filters.'}</Text>}</>}
    </ScrollView>
    {filterOpen && <Sheet title="Filters" close={() => setFilterOpen(false)} footer={<View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button label="Reset All" onPress={() => { setDraftCategories([]); setDraft({ dateFrom:'', dateTo:'', price:'All', gender:'All', verifiedOnly:false }); }} /></View><View style={{ flex: 1 }}><Button label="Apply Filters" onPress={() => { setCategories(draftCategories); setDateFrom(draft.dateFrom); setDateTo(draft.dateTo); setPrice(draft.price); setGender(draft.gender); setVerifiedOnly(draft.verifiedOnly); setFilterOpen(false); }} /></View></View>}>
      <Text style={{ color:c.text,fontWeight:'700',fontSize:14 }}>Date Filter</Text><View style={{ flexDirection:'row',gap:10 }}>{(['dateFrom','dateTo'] as const).map((key,index) => <View key={key} style={{ flex:1,gap:7 }}><Text style={{ color:c.muted,fontSize:10 }}>{index ? 'To' : 'From'}</Text>{Platform.OS==='web' ? <View style={{ minHeight:44,backgroundColor:c.card,borderWidth:1,borderColor:c.border,borderRadius:9,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8,overflow:'hidden' }}><Icon name="calendar-outline" color={c.muted} size={15}/><Text style={{ color:c.text,fontSize:12 }}>{draft[key] ? new Date(`${draft[key]}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}) : 'Today'}</Text>{React.createElement('input',{type:'date','aria-label':index?'Date to':'Date from',value:draft[key],onChange:(e:React.ChangeEvent<HTMLInputElement>)=>setDraft(v=>({...v,[key]:e.target.value})),style:{position:'absolute',inset:0,width:'100%',height:'100%',opacity:0,cursor:'pointer',colorScheme:useDarkColorScheme(c)}})}</View> : <Pressable style={{ backgroundColor:c.card,borderWidth:1,borderColor:c.border,borderRadius:9,padding:12 }}><Text style={{ color:c.text }}>{draft[key]||'Today'}</Text></Pressable>}</View>)}</View>
      <Text style={{ color:c.text,fontWeight:'700',fontSize:14 }}>Price</Text><Pills values={['All','Free','Paid']} selected={draft.price} onChange={value=>setDraft(v=>({...v,price:value}))} />
      <Text style={{ color:c.text,fontWeight:'700',fontSize:14 }}>Gender Preference</Text><Pills values={['All','Male','Female']} selected={draft.gender} onChange={value=>setDraft(v=>({...v,gender:value}))} /><Pressable accessibilityRole="radio" accessibilityState={{ checked:draft.gender==='Non-binary' }} onPress={()=>setDraft(v=>({...v,gender:'Non-binary'}))} style={{ alignSelf:'flex-start',backgroundColor:draft.gender==='Non-binary'?purple:c.card,borderRadius:20,paddingHorizontal:18,paddingVertical:9 }}><Text style={{ color:draft.gender==='Non-binary'?'#FFF':c.muted,fontSize:13 }}>Non-binary</Text></Pressable>
      <View style={{ flexDirection:'row',alignItems:'center',gap:12,paddingVertical:6 }}><View style={{ flex:1,gap:4 }}><Text style={{ color:c.text,fontWeight:'700',fontSize:14 }}>Exclusive for Verified Users</Text><Text style={{ color:c.muted,fontSize:10 }}>Show activities restricted to verified profiles.</Text></View><Switch accessibilityLabel="Exclusive for Verified Users" value={draft.verifiedOnly} onValueChange={value=>setDraft(v=>({...v,verifiedOnly:value}))} trackColor={{true:purple,false:c.border}} /></View>
      <Text style={{ color:c.text,fontWeight:'700',fontSize:14 }}>Categories</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 9 }}>{INTEREST_CATEGORIES.filter(value => !/qa|automation|test/i.test(value)).map(value => { const selected = draftCategories.includes(value); return <Pressable accessibilityRole="checkbox" accessibilityState={{ checked: selected }} key={value} onPress={() => setDraftCategories(current => selected ? current.filter(item => item !== value) : [...current, value])} style={{ width: '47%', minHeight: 58, borderWidth: 1, borderColor: selected ? '#8E7CFF' : c.border, backgroundColor: selected ? '#6D5AEF24' : c.card, borderRadius: 10, padding: 10, justifyContent: 'center' }}><Text style={{ color: selected ? '#A99CFF' : c.text, fontSize: 11, fontWeight: '600' }}>{value}</Text></Pressable>; })}</View>
    </Sheet>}
  </Page>;
}
function useDarkColorScheme(c: ReturnType<typeof usePalette>) { return c.bg === '#101824' ? 'dark' : 'light'; }
export function productionActivity(a: Omit<ActivityListItem, 'viewerState'> & { viewerState?: ActivityListItem['viewerState'] }): Activity { return { id: a.id, title: a.title, category: a.category, when: a.startsAt || 'To Be Decided', where: a.locationName, latitude: a.latitude, longitude: a.longitude, price: a.priceInr ? `₹${a.priceInr}` : 'Free', seats: a.capacity || 0, joined: 0, image: a.coverUrl || Asset.fromModule(require('../../../assets/wenitro-logo-transparent.png')).uri, host: a.owner?.username || a.owner?.fullName || 'Host', hostAvatar: a.owner?.avatarUrl || undefined, ownerId: a.ownerId, startsAt: a.startsAt || undefined, end: a.endsAt || undefined, endsAt: a.endsAt || undefined, closes: a.registrationClosesAt || undefined, registrationClosesAt: a.registrationClosesAt || undefined, status: a.status, description: a.description || '', visibility: a.visibility, activityType: a.activityType, joinType: a.joinType, communityId: a.communityId, locationInstruction: a.locationInstruction || undefined, verifiedOnly: a.verifiedOnly, ageMin: a.ageMin, ageMax: a.ageMax, genderPreference: a.genderPreference, viewerStatus: a.viewerState?.participation?.status === 'going' ? 'going' : a.viewerState?.participation?.status || null }; }
export function ReferenceSearch({ back, openActivity, openProfile, openCommunity, setData }: { back: () => void; openActivity: (id: string) => void; openProfile: (id: string) => void; openCommunity: (id: string) => void; setData: React.Dispatch<React.SetStateAction<AppData>> }) {
 const c = usePalette(); const [scope, setScope] = useState('Activities'), [query, setQuery] = useState(''), [page, setPage] = useState(1), [rows, setRows] = useState<{ id: string; name: string; subtitle: string; image?: string }[]>([]), [more, setMore] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState('');
 useEffect(() => { setPage(1); setRows([]); }, [scope, query]);
 useEffect(() => { const controller = new AbortController(); let active = true; setError(''); if (query.trim().length < 2) { setRows([]); setMore(false); setLoading(false); return; } setLoading(true); const timer = setTimeout(() => { void (async () => {
  try { let result: typeof rows = [], hasMore = false;
   if (scope === 'Activities') { const response = await activitiesProductionService.discover({ search: query, page, pageSize: 20, signal: controller.signal }); const prepared = await prepareReferenceActivities(response.items); result = prepared.map(a => ({ id: a.id, name: a.title, subtitle: a.where, image: a.image })); hasMore = response.hasMore; if (active) setData(current => ({ ...current, activities: [...current.activities.filter(a => !response.items.some(r => r.id === a.id)), ...prepared] })); }
   else if (scope === 'Communities') { const response = await communitiesProductionService.discover({ query, page, pageSize: 20 }); result = response.items.map(a => ({ id: a.id, name: a.name, subtitle: a.category, image: a.imageUrl || undefined })); hasMore = response.hasMore; }
   else { const safe = query.trim().replace(/[%_,()."\\]/g, ' ').slice(0, 80); const response = await supabase.from('tbl_users').select('id,username,fullname,profile_image').or(`username.ilike.%${safe}%,fullname.ilike.%${safe}%`).order('id').range((page - 1) * 20, page * 20).abortSignal(controller.signal); if (response.error) throw response.error; hasMore = (response.data || []).length > 20; result = (response.data || []).slice(0, 20).map(p => ({ id: String(p.id), name: p.fullname || p.username, subtitle: '@' + p.username, image: p.profile_image || undefined })); }
   if (active) { setRows(current => page === 1 ? result : [...current, ...result]); setMore(hasMore); }
  } catch (e: any) { if (active) setError(e.message); } finally { if (active) setLoading(false); }
 })(); }, 350); return () => { active = false; controller.abort(); clearTimeout(timer); }; }, [scope, query, page]);
 return <Page><View style={{ flexDirection: 'row', alignItems: 'center' }}><Action name="arrow-back" label="Back" onPress={back} /><View style={{ flex: 1 }}><SearchField accessibilityLabel={`Search ${scope.toLowerCase()}`} placeholder={`Search ${scope.toLowerCase()}...`} value={query} onChangeText={setQuery} autoFocus /></View></View><Pills values={['Activities', 'People', 'Communities']} selected={scope} onChange={setScope} /><ErrorLine text={error} />{loading && !rows.length ? <Skeleton /> : <ScrollView contentContainerStyle={{ padding: 15 }}>{rows.map(r => <Pressable accessibilityRole="button" key={r.id} onPress={() => scope === 'Activities' ? openActivity(r.id) : scope === 'People' ? openProfile(r.id) : openCommunity(r.id)} style={[ui.row, { borderBottomWidth: 1, borderColor: c.border, paddingHorizontal: 0 }]}>{r.image ? <Image source={{ uri: r.image }} style={ui.avatar} /> : <Icon name={scope === 'People' ? 'person-circle-outline' : scope === 'Activities' ? 'calendar-outline' : 'people-outline'} size={35} color={c.muted} />}<View style={{ flex: 1, gap: 5 }}><Text style={{ color: c.text, fontSize: 13 }}>{r.name}</Text><Text style={{ color: c.muted, fontSize: 11 }}>{r.subtitle}</Text></View></Pressable>)}{more && <Button label="Load more" busy={loading} onPress={() => setPage(p => p + 1)} />}</ScrollView>}</Page>;
}

function distanceKm(lat1: number, lng1: number, lat2: number, lng2: number) { const r = Math.PI / 180; const a = Math.sin((lat2 - lat1) * r / 2) ** 2 + Math.cos(lat1 * r) * Math.cos(lat2 * r) * Math.sin((lng2 - lng1) * r / 2) ** 2; return 6371 * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(Math.max(0, 1 - a))); }

export async function prepareReferenceActivities(items: Parameters<typeof productionActivity>[0][]): Promise<Activity[]> {
 const paths = [...new Set(items.flatMap(a => a.coverUrl && !/^https?:\/\//.test(a.coverUrl) && !a.coverUrl.startsWith('data:') && !a.coverUrl.startsWith('media/events/') ? [a.coverUrl] : []))];
 const [counts, likesResult, signed] = await Promise.all([loadActivityParticipantCounts(items.map(a => a.id)), items.length ? supabase.from('tbl_event_likes').select('event_id').in('event_id', items.map(a => Number(a.id))) : Promise.resolve({ data: [], error: null }), paths.length ? supabase.storage.from('activity-media').createSignedUrls(paths, 3600) : Promise.resolve({ data: [], error: null })]);
 if (likesResult.error) throw likesResult.error;
 const likeCounts = new Map<string, number>(); for (const row of likesResult.data || []) { const id = String(row.event_id); likeCounts.set(id, (likeCounts.get(id) || 0) + 1); }
 const urls = new Map((signed.data || []).map(row => [row.path, row.signedUrl]));
 return items.map(a => ({ ...productionActivity(a), joined: counts.get(a.id) || 0, likeCount: likeCounts.get(a.id) || 0, image: a.coverUrl && /^(https?:|data:)/.test(a.coverUrl) ? a.coverUrl : urls.get(a.coverUrl || '') || Asset.fromModule(require('../../../assets/wenitro-logo-transparent.png')).uri }));
}
