import React, { useEffect, useState } from 'react';
import { Image, Pressable, ScrollView, Text, View } from 'react-native';
import type { AppData } from '../../../App';
import { communitiesProductionService, type CommunitySummary } from '../../services/communities-production';
import { supabase } from '../../lib/supabase';
import { subscribeToAppForeground } from '../../services/app-freshness';
import { Action, Button, ErrorLine, Header, Icon, Page, Pills, SearchField, Skeleton, ui, usePalette, purple } from './ui';
export function ReferenceMessages({ data, tab, setTab, filter, setFilter, openConversation, startConversation, openCommunity, createCommunity, openLegacy }: { data: AppData; tab: string; setTab: (tab: string) => void; filter: string; setFilter: (filter: string) => void; openProfile: (id: string) => void; openConversation: (id: string) => void; startConversation: (person: { id: number; username: string; fullname: string; profile_image: string }) => Promise<void>; openCommunity: (c: CommunitySummary) => void; createCommunity: () => void; openLegacy: () => void }) {
 const c = usePalette(); const [query, setQuery] = useState(''), [rows, setRows] = useState<CommunitySummary[]>([]), [page, setPage] = useState(1), [more, setMore] = useState(false), [loading, setLoading] = useState(false), [error, setError] = useState(''), [version, setVersion] = useState(0);
 const [people, setPeople] = useState<{ id: number; username: string; fullname: string; profile_image: string }[]>([]);
 const [inbox, setInbox] = useState<Record<string, any>>({});
 useEffect(() => { setQuery(''); setPage(1); }, [tab]);
 useEffect(() => { setPage(1); }, [query, filter]);
 useEffect(() => subscribeToAppForeground(() => setVersion(v => v + 1)), []);
 useEffect(() => { if (tab !== 'Communities') return; let active = true; setLoading(true); const timer = setTimeout(() => { void Promise.all([communitiesProductionService.discover({ query, membership: filter.toLowerCase() as 'all' | 'joined' | 'created', page, pageSize: 25 }), supabase.rpc('list_chat_inbox', { p_message_limit: 1 })]).then(([communities, inbox]) => { if (!active) return; if (inbox.error) throw inbox.error; setRows(current => page === 1 ? communities.items : [...current, ...communities.items]); setMore(communities.hasMore); setInbox(Object.fromEntries((inbox.data || []).map((r: any) => [String(r.id || r.room_id), r]))); setError(''); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); }, query ? 300 : 0); return () => { active = false; clearTimeout(timer); }; }, [tab, query, filter, page, version]);
 useEffect(() => { let active = true; if (tab !== 'Chats' || query.trim().length < 2) { setPeople([]); return; }
 const timer = setTimeout(() => { const safe = query.trim().replace(/[%_,()."\\]/g, ' ').slice(0, 80); void supabase.from('tbl_users').select('id,username,fullname,profile_image').or(`username.ilike.%${safe}%,fullname.ilike.%${safe}%`).limit(20).then(({ data: result, error }) => { if (active) { if (error) setError(error.message); else setPeople((result || []).filter(p => String(p.id) !== data.userId)); } }); }, 350);
 return () => { active = false; clearTimeout(timer); };
 }, [tab, query]);
 const conversations = data.conversations.filter(r => r.roomType !== 'community' && !data.communities.some(cm => cm.id === r.id) && (tab === 'Chats' ? r.type === 'People' : r.type === 'Groups') && r.name.toLowerCase().includes(query.toLowerCase()));
 const searchPeople = people.filter(person => !conversations.some(conversation => conversation.userId === String(person.id)));
 return <Page><Header title="Messages">{tab !== 'Communities' && <Action name="add-circle-outline" label="Stories, people and group tools" onPress={openLegacy} />}</Header><Pills underline values={['Chats', 'Groups', 'Communities']} selected={tab} onChange={setTab} /><SearchField accessibilityLabel={tab === 'Chats' ? 'Search chats or users' : tab === 'Groups' ? 'Search group chats' : 'Search communities'} placeholder={tab === 'Chats' ? 'Search chats or users...' : tab === 'Groups' ? 'Search group chats...' : 'Search communities...'} value={query} onChangeText={setQuery} />{tab === 'Communities' && <Pills values={['All', 'Joined', 'Created']} selected={filter} onChange={setFilter} />}<ErrorLine text={error} />
 {tab === 'Communities' && loading && page === 1 ? <Skeleton count={5} /> : <ScrollView contentContainerStyle={{ paddingHorizontal: 15, paddingBottom: 90 }}>{tab === 'Communities' ? rows.map(room => {
 const conv = data.conversations.find(v => v.id === room.id); const remote = inbox[room.id]; const message = conv?.messages[conv.messages.length - 1]; const latest = remote?.last_message;
 const text = message?.text || latest?.content || latest?.body || ''; const kind = message?.messageType || latest?.message_type; const preview = kind === 'image' ? 'Photo' : kind === 'video' ? 'Video' : kind === 'poll' ? 'Poll' : text;
 const mine = message ? message.mine : String(latest?.sender_id) === data.userId; const at = conv?.lastMessageAt || latest?.created_at || remote?.last_message_at;
 return <Pressable accessibilityRole="button" key={room.id} onPress={() => openCommunity(room)} style={[ui.row, { paddingHorizontal: 0, minHeight: 80, borderBottomWidth: 1, borderColor: c.border }]}>{room.imageUrl ? <Image source={{ uri: room.imageUrl }} style={ui.avatar} /> : <View style={[ui.avatar, { backgroundColor: c.card, alignItems: 'center', justifyContent: 'center' }]}><Icon name="people-outline" color={purple} /></View>}<View style={{ flex: 1, gap: 4 }}><Text numberOfLines={1} style={{ color: c.text, fontSize: 14, fontWeight: '600' }}>{room.name}</Text><Text style={{ color: '#9C90F4', fontSize: 10 }}>{room.category}</Text>{preview ? <Text numberOfLines={1} style={{ color: c.muted, fontSize: 11 }}>{mine ? 'You: ' : ''}{preview}</Text> : null}</View>{at && <Text style={{ color: c.muted, fontSize: 9 }}>{new Date(at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text>}</Pressable>;
 }) : <>{conversations.length ? <Text style={[ui.section, { color: c.muted, marginTop: 14 }]}>ACTIVE CONVERSATIONS</Text> : null}{conversations.map(conv => { const last = conv.messages[conv.messages.length - 1]; const at = conv.lastMessageAt || last?.createdAt; return <Pressable accessibilityRole="button" key={conv.id} onPress={() => openConversation(conv.id)} style={[ui.row, { paddingHorizontal: 0, borderBottomWidth: 1, borderColor: c.border, minHeight: 77 }]}>{conv.avatar ? <Image source={{ uri: conv.avatar }} style={ui.avatar} /> : <Icon name="person-circle-outline" size={44} color={c.muted} />}<View style={{ flex: 1, gap: 6 }}><Text style={{ color: c.text, fontSize: 14, fontWeight: '600' }}>{conv.name}</Text><Text style={{ color: c.muted, fontSize: 11 }} numberOfLines={1}>{last ? `${last.mine ? 'You: ' : ''}${last.text || (last.messageType === 'video' ? 'Video' : 'Photo')}` : 'No messages yet'}</Text></View><View style={{ alignItems: 'flex-end', gap: 7 }}>{at ? <Text style={{ color: c.muted, fontSize: 9 }}>{new Date(at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Text> : null}{conv.unread > 0 && <Text style={{ color: 'white', backgroundColor: purple, borderRadius: 11, paddingHorizontal: 6, paddingVertical: 3, fontSize: 9 }}>{conv.unread}</Text>}</View></Pressable>; })}</>}
 {tab === 'Chats' && searchPeople.length ? <Text style={[ui.section, { color: c.muted, marginTop: 16 }]}>PEOPLE</Text> : null}
 {tab === 'Chats' && searchPeople.map(p => <Pressable accessibilityRole="button" key={'person:' + p.id} onPress={() => void startConversation(p)} style={[ui.row, { paddingHorizontal: 0 }]}>{p.profile_image ? <Image source={{ uri: p.profile_image }} style={ui.avatar} /> : <Icon name="person-circle-outline" size={44} color={c.muted} />}<View style={{ flex: 1, gap: 5 }}><Text style={{ color: c.text, fontSize: 13 }}>{p.fullname || p.username}</Text><Text style={{ color: c.muted, fontSize: 11 }}>@{p.username}</Text></View><Icon name="chatbubble-outline" color={purple} size={20} /></Pressable>)}
 {!loading && !(tab === 'Communities' ? rows.length : conversations.length + searchPeople.length) && <Text style={{ color: c.muted, fontSize: 13, textAlign: 'center', marginTop: 38 }}>{tab === 'Chats' ? 'No personal chats yet.' : tab === 'Groups' ? 'No event group chats yet.' : 'No communities found.'}</Text>}{tab === 'Communities' && more && <Button label="Load more" busy={loading} onPress={() => setPage(p => p + 1)} />}</ScrollView>}
 {tab === 'Communities' && <Pressable accessibilityRole="button" accessibilityLabel="Create Community" onPress={createCommunity} style={{ position: 'absolute', bottom: 21, right: 20, width: 50, height: 50, borderRadius: 27, backgroundColor: purple, alignItems: 'center', justifyContent: 'center' }}><Icon name="add" color="#FFF" size={28} /></Pressable>}
 </Page>;
}
