import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Image, Pressable, ScrollView, Text, View } from 'react-native';
import type { Activity } from '../../../App';
import { activitiesProductionService } from '../../services/activities-production';
import { profileProductionService } from '../../services/profile-production';
import { referenceDeltaService, type EmergencyContact, type NitroLedgerRow } from '../../services/reference-delta';
import { supabase } from '../../lib/supabase';
import { prepareReferenceActivities } from './feed-search';
import { Button, ErrorLine, Field, Header, Icon, Page, Pills, Sheet, Skeleton, usePalette, purple } from './ui';

const ended = (activity: Activity) => activity.status === 'completed' || Boolean(activity.endsAt && Date.parse(activity.endsAt) <= Date.now());

export function ReferenceVerification({ back }: { back: () => void }) {
  const c = usePalette();
  const [phone, setPhone] = useState('');
  const [otp, setOtp] = useState('');
  const [otpSent, setOtpSent] = useState(false);
  const [phoneVerified, setPhoneVerified] = useState(false);
  const [trustScore, setTrustScore] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const lock = useRef(false);
  const load = async () => {
    const [state, metrics, auth] = await Promise.all([profileProductionService.getVerificationState(), supabase.rpc('my_profile_metrics'), supabase.auth.getUser()]);
    if (metrics.error) throw metrics.error;
    if (auth.error) throw auth.error;
    setPhoneVerified(state.phoneVerified);
    setTrustScore(typeof (metrics.data as any)?.trust_score === 'number' ? Number((metrics.data as any).trust_score) : null);
    setPhone(auth.data.user?.phone?.replace(/^\+91/, '') || '');
  };
  useEffect(() => { let active = true; void load().catch(e => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const run = async (action: () => Promise<unknown>) => { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { await action(); } catch (e: any) { setError(e.message || 'Verification could not continue.'); } finally { lock.current = false; setBusy(false); } };
  return <Page><Header title="Verify Your Account" back={back} />{loading ? <Skeleton /> : <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 18, gap: 18, paddingBottom: 40 }}>
    <View style={{ borderRadius: 18, padding: 18, backgroundColor: c.card, borderWidth: 1, borderColor: c.border, flexDirection: 'row', alignItems: 'center', gap: 16 }}><View style={{ width: 70, height: 70, borderRadius: 36, borderWidth: 6, borderColor: phoneVerified ? '#52BE86' : c.border, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: c.text, fontSize: 22, fontWeight: '800' }}>{trustScore ?? '—'}</Text><Text style={{ color: c.muted, fontSize: 8 }}>/100</Text></View><View style={{ flex: 1, gap: 5 }}><Text style={{ color: c.text, fontSize: 17, fontWeight: '700' }}>Trust Score</Text><Text style={{ color: c.muted, fontSize: 11, lineHeight: 17 }}>{trustScore === null ? 'A Trust Score has not been calculated for this account.' : 'This is your current account Trust Score.'}</Text></View></View>
    <View style={{ backgroundColor: c.card, borderRadius: 16, padding: 17, borderWidth: 1, borderColor: c.border, gap: 13 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ width: 30, height: 30, borderRadius: 16, backgroundColor: phoneVerified ? '#D8F7E7' : '#ECE9FF', alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: phoneVerified ? '#198457' : purple, fontWeight: '800' }}>{phoneVerified ? '✓' : '1'}</Text></View><View style={{ flex: 1 }}><Text style={{ color: c.text, fontSize: 15, fontWeight: '700' }}>Phone</Text><Text style={{ color: c.muted, fontSize: 10 }}>{phoneVerified ? 'Verified' : 'Verify with a one-time password'}</Text></View></View>
      {!phoneVerified && <><View style={{ flexDirection: 'row', gap: 8, alignItems: 'center' }}><View style={{ minHeight: 46, justifyContent: 'center', paddingHorizontal: 13, borderWidth: 1, borderColor: c.border, borderRadius: 9, backgroundColor: c.bg }}><Text style={{ color: c.text }}>+91</Text></View><Field accessibilityLabel="Phone number" keyboardType="phone-pad" maxLength={10} value={phone} onChangeText={value => setPhone(value.replace(/\D/g, '').slice(0, 10))} placeholder="10-digit mobile number" style={{ flex: 1 }} /></View>{otpSent && <Field accessibilityLabel="Phone OTP" keyboardType="number-pad" maxLength={6} value={otp} onChangeText={value => setOtp(value.replace(/\D/g, '').slice(0, 6))} placeholder="6-digit OTP" />}
      <Button label={otpSent ? 'Verify Phone' : 'Add & Verify Phone'} busy={busy} disabled={otpSent ? otp.length !== 6 : phone.length !== 10} onPress={() => void run(async () => { if (!otpSent) { await referenceDeltaService.requestPhoneChange(phone); setOtpSent(true); } else { await referenceDeltaService.verifyPhoneChange(phone, otp); setPhoneVerified(true); setOtpSent(false); setOtp(''); } })} /></>}
    </View>
    <View style={{ backgroundColor: c.card, borderRadius: 16, padding: 17, borderWidth: 1, borderColor: c.border, gap: 13, opacity: phoneVerified ? 1 : .62 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}><View style={{ width: 30, height: 30, borderRadius: 16, backgroundColor: c.inset, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: c.muted, fontWeight: '800' }}>2</Text></View><View style={{ flex: 1 }}><Text style={{ color: c.text, fontSize: 15, fontWeight: '700' }}>Aadhaar Number</Text><Text style={{ color: c.muted, fontSize: 10 }}>{phoneVerified ? 'Provider connection required' : 'Complete Step 1 first'}</Text></View><Icon name="lock-closed-outline" color={c.muted} /></View><Field accessibilityLabel="Aadhaar Number" editable={false} placeholder="Aadhaar verification unavailable" /><Text style={{ color: '#D1783E', fontSize: 10, lineHeight: 16 }}>AADHAAR PROVIDER/VERIFICATION NOT IMPLEMENTED</Text></View>
    <ErrorLine text={error} />
  </ScrollView>}</Page>;
}

const RELATIONS = ['Parent', 'Spouse', 'Sibling', 'Friend', 'Partner', 'Guardian', 'Other'];
export function ReferenceEmergencyContact({ back }: { back: () => void }) {
  const c = usePalette();
  const [contact, setContact] = useState<EmergencyContact>({ contact_name: '', relation: '', countrycode: '+91', phone_number: '', is_verified: false });
  const [relations, setRelations] = useState(false), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [saved, setSaved] = useState(false), [error, setError] = useState('');
  useEffect(() => { let active = true; void referenceDeltaService.getEmergencyContact().then(row => { if (active && 'contact_name' in row) setContact(row as EmergencyContact); }).catch(e => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  const update = (patch: Partial<EmergencyContact>) => { setContact(value => ({ ...value, ...patch })); setSaved(false); };
  const valid = contact.contact_name.trim().length >= 2 && Boolean(contact.relation) && /^[6-9]\d{9}$/.test(contact.phone_number);
  return <Page><Header title="Emergency Contact" back={back} />{loading ? <Skeleton /> : <ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 18, gap: 17 }}><View style={{ backgroundColor: c.isDark ? '#38232B' : '#FFF0F1', borderWidth: 1, borderColor: c.isDark ? '#72404D' : '#F4B8BF', borderRadius: 14, padding: 14, flexDirection: 'row', gap: 11 }}><Icon name="warning-outline" color={c.isDark ? '#FF8A99' : '#C93D51'} /><View style={{ flex: 1, gap: 4 }}><Text style={{ color: c.isDark ? '#FFA0AD' : '#A52237', fontWeight: '700', fontSize: 13 }}>SOS Quick Contact</Text><Text style={{ color: c.isDark ? '#D5A4AC' : '#8D3D48', fontSize: 10, lineHeight: 16 }}>This trusted contact may be used for safety escalation. Keep the number current.</Text></View></View>
    <View><Text style={{ color: c.text, fontSize: 12, fontWeight: '600', marginBottom: 8 }}>Contact Name</Text><Field accessibilityLabel="Contact Name" value={contact.contact_name} onChangeText={value => update({ contact_name: value })} maxLength={100} placeholder="Enter full name" /></View>
    <View><Text style={{ color: c.text, fontSize: 12, fontWeight: '600', marginBottom: 8 }}>Relation</Text><Pressable accessibilityRole="button" onPress={() => setRelations(true)} style={{ minHeight: 46, borderWidth: 1, borderColor: c.border, backgroundColor: c.card, borderRadius: 9, padding: 12, flexDirection: 'row', alignItems: 'center' }}><Text style={{ color: contact.relation ? c.text : c.muted, flex: 1 }}>{contact.relation || 'Select relation'}</Text><Icon name="chevron-down" color={c.muted} size={17} /></Pressable></View>
    <View><Text style={{ color: c.text, fontSize: 12, fontWeight: '600', marginBottom: 8 }}>Phone Number</Text><View style={{ flexDirection: 'row', gap: 8 }}><View style={{ minHeight: 46, borderWidth: 1, borderColor: c.border, backgroundColor: c.card, borderRadius: 9, paddingHorizontal: 13, justifyContent: 'center' }}><Text style={{ color: c.text }}>+91</Text></View><Field accessibilityLabel="Emergency phone number" value={contact.phone_number} onChangeText={value => update({ phone_number: value.replace(/\D/g, '').slice(0, 10) })} keyboardType="phone-pad" maxLength={10} placeholder="10-digit mobile number" style={{ flex: 1 }} /></View><Text style={{ color: c.muted, fontSize: 10, marginTop: 7 }}>Enter a valid Indian mobile number beginning with 6, 7, 8, or 9.</Text></View>
    {saved && <Text accessibilityRole="alert" style={{ color: '#23845D', fontSize: 12 }}>Emergency contact saved privately.</Text>}<ErrorLine text={error} /><Button label="Save Contact" busy={busy} disabled={!valid} onPress={() => { setBusy(true); setError(''); void referenceDeltaService.saveEmergencyContact({ name: contact.contact_name, relation: contact.relation, phone: contact.phone_number }).then(row => { setContact(row); setSaved(true); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }} />
  </ScrollView>}{relations && <Sheet title="Relation" centered close={() => setRelations(false)}>{RELATIONS.map(value => <Pressable accessibilityRole="radio" accessibilityState={{ checked: contact.relation === value }} key={value} onPress={() => { update({ relation: value }); setRelations(false); }} style={{ minHeight: 46, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10 }}><Text style={{ color: c.text, flex: 1 }}>{value}</Text>{contact.relation === value && <Icon name="checkmark" color={purple} />}</Pressable>)}</Sheet>}</Page>;
}

export function ReferenceActivityHistory({ userId, back, openActivity }: { userId: string; back: () => void; openActivity: (id: string) => void }) {
  const c = usePalette(); const [rows, setRows] = useState<Array<Activity & { historyRole: 'Hosted' | 'Joined' }>>([]); const [loading, setLoading] = useState(true), [error, setError] = useState(''), [filterOpen, setFilterOpen] = useState(false); const [role, setRole] = useState('All'), [status, setStatus] = useState('All'), [draftRole, setDraftRole] = useState('All'), [draftStatus, setDraftStatus] = useState('All');
  useEffect(() => { let active = true; void Promise.all([activitiesProductionService.listHosted({ pageSize: 100 }), activitiesProductionService.discover({ pageSize: 100, upcomingOnly: false, sort: 'latest' })]).then(async ([hosted, discovered]) => { const hostedRows = await prepareReferenceActivities(hosted.items); const joinedSource = discovered.items.filter(item => item.viewerState.participation && item.ownerId !== userId); const joinedRows = await prepareReferenceActivities(joinedSource); const map = new Map<string, Activity & { historyRole: 'Hosted' | 'Joined' }>(); hostedRows.forEach(row => map.set(row.id, { ...row, historyRole: 'Hosted' })); joinedRows.forEach(row => map.set(row.id, { ...row, historyRole: 'Joined' })); if (active) setRows([...map.values()].sort((a,b) => Date.parse(b.startsAt || '1970-01-01') - Date.parse(a.startsAt || '1970-01-01'))); }).catch(e => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, [userId]);
  const shown = useMemo(() => rows.filter(row => (role === 'All' || row.historyRole === role) && (status === 'All' || (status === 'Completed') === ended(row))), [rows, role, status]);
  return <Page><Header title="Activity History" back={back}><Pressable accessibilityRole="button" accessibilityLabel="Filter Activity History" onPress={() => { setDraftRole(role); setDraftStatus(status); setFilterOpen(true); }} style={{ padding: 12 }}><Icon name="options-outline" /></Pressable></Header><ErrorLine text={error} />{loading ? <Skeleton /> : <ScrollView contentContainerStyle={{ padding: 16, gap: 12, paddingBottom: 34 }}>{shown.map(row => <Pressable accessibilityRole="button" accessibilityLabel={`Open ${row.title}`} key={row.id} onPress={() => openActivity(row.id)} style={{ backgroundColor: c.card, borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: c.border }}><Image source={{ uri: row.image }} style={{ width: '100%', height: 122, backgroundColor: c.inset }} /><View style={{ padding: 13, gap: 7 }}><View style={{ flexDirection: 'row', alignItems: 'center' }}><Text style={{ color: c.text, fontSize: 14, fontWeight: '700', flex: 1 }}>{row.title}</Text><Text style={{ color: ended(row) ? '#64748B' : '#2E9B69', fontSize: 9, fontWeight: '700' }}>{ended(row) ? 'COMPLETED' : 'UPCOMING'}</Text></View><Text style={{ color: purple, fontSize: 10 }}>{row.historyRole}</Text><Text style={{ color: c.muted, fontSize: 10 }}>{row.when} · {row.where}</Text></View></Pressable>)}{!shown.length && <Text style={{ color: c.muted, textAlign: 'center', paddingTop: 70 }}>No activities match these filters.</Text>}</ScrollView>}{filterOpen && <Sheet title="Filter Activity History" centered close={() => setFilterOpen(false)}><Text style={{ color: c.text, fontSize: 13, fontWeight: '700' }}>Role</Text><Pills values={['All','Hosted','Joined']} selected={draftRole} onChange={setDraftRole} /><Text style={{ color: c.text, fontSize: 13, fontWeight: '700' }}>Status</Text><Pills values={['All','Upcoming','Completed']} selected={draftStatus} onChange={setDraftStatus} /><View style={{ flexDirection: 'row', gap: 10 }}><View style={{ flex: 1 }}><Button label="Reset" onPress={() => { setDraftRole('All'); setDraftStatus('All'); }} /></View><View style={{ flex: 1 }}><Button label="Apply" onPress={() => { setRole(draftRole); setStatus(draftStatus); setFilterOpen(false); }} /></View></View></Sheet>}</Page>;
}

export function ReferenceNitroHistory({ back }: { back: () => void }) {
  const c = usePalette(); const [balance, setBalance] = useState(0), [rows, setRows] = useState<NitroLedgerRow[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState('');
  useEffect(() => { let active = true; void referenceDeltaService.listNitroHistory().then(result => { if (active) { setBalance(Number(result.balance || 0)); setRows(result.items || []); } }).catch(e => active && setError(e.message)).finally(() => active && setLoading(false)); return () => { active = false; }; }, []);
  return <Page><Header title="Nitro History" back={back} />{loading ? <Skeleton /> : <ScrollView contentContainerStyle={{ padding: 16, gap: 16 }}><View style={{ borderRadius: 17, padding: 18, backgroundColor: balance >= 500 ? '#6555EA' : c.card, borderWidth: 1, borderColor: balance >= 500 ? '#6555EA' : c.border, flexDirection: 'row', alignItems: 'center', gap: 12 }}><Icon name={balance >= 500 ? 'gift-outline' : 'lock-closed-outline'} color={balance >= 500 ? '#FFF' : '#C0A72B'} size={29} /><View style={{ flex: 1, gap: 5 }}><Text style={{ color: balance >= 500 ? '#FFF' : c.text, fontSize: 15, fontWeight: '700' }}>{balance >= 500 ? 'Nitro Store Unlocked' : 'Nitro Store Locked'}</Text><Text style={{ color: balance >= 500 ? '#EEE9FF' : c.muted, fontSize: 11 }}>{balance} pts{balance < 500 ? ` · Earn ${500-balance} more to unlock` : ''}</Text></View></View><Text style={{ color: c.text, fontSize: 17, fontWeight: '700' }}>Point Ledger</Text><ErrorLine text={error} />{rows.map(row => <View key={row.id} style={{ backgroundColor: c.card, borderRadius: 12, padding: 14, borderWidth: 1, borderColor: c.border, flexDirection: 'row', alignItems: 'center', gap: 12 }}><View style={{ width: 39, height: 39, borderRadius: 20, backgroundColor: row.points >= 0 ? '#DFF6E9' : '#FDE5E8', alignItems: 'center', justifyContent: 'center' }}><Icon name="flash" color={row.points >= 0 ? '#2D9666' : '#C93D51'} size={19} /></View><View style={{ flex: 1, gap: 4 }}><Text style={{ color: c.text, fontSize: 12, fontWeight: '600' }}>{row.description}</Text><Text style={{ color: c.muted, fontSize: 9 }}>{new Date(row.created_at).toLocaleString()}</Text></View><Text style={{ color: row.points >= 0 ? '#2D9666' : '#C93D51', fontWeight: '800' }}>{row.points >= 0 ? '+' : ''}{row.points}</Text></View>)}{!rows.length && !error && <View style={{ alignItems: 'center', paddingTop: 55, gap: 12 }}><Icon name="receipt-outline" color={c.muted} size={42} /><Text style={{ color: c.text, fontWeight: '700' }}>No transactions yet</Text><Text style={{ color: c.muted, fontSize: 11, textAlign: 'center', lineHeight: 17 }}>Real Nitro point entries will appear here when your account earns or spends points.</Text></View>}</ScrollView>}</Page>;
}
