import { storeEligible } from '../../domain/profile-signals';
import React, { useEffect, useRef, useState } from 'react';
import { Linking, Pressable, ScrollView, Share, Switch, Text, View } from 'react-native';
import Constants from 'expo-constants';
import type { AppData, Screen } from '../../../App';
import { profileProductionService, type PrivacyPreferences } from '../../services/profile-production';
import { authService } from '../../services/wenitro';
import { supabase } from '../../lib/supabase';
import { Button, ErrorLine, Field, Header, Icon, Page, Sheet, Skeleton, ui, usePalette, purple } from './ui';
export function ReferenceSettings({ data, setData, back, go }: { data: AppData; setData: React.Dispatch<React.SetStateAction<AppData>>; back: () => void; go: (screen: Screen) => void }) {
 const c = usePalette(); const [confirm, setConfirm] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
 const groups: [string, [string, string, () => void][]][] = [
 ['PROFILE & SAFETY', [['Verify Your Account', 'shield-checkmark-outline', () => go('verification')], ['Emergency Contact', 'alert-circle-outline', () => go('emergency')], ['Activity History', 'calendar-outline', () => go('activityHistory')], ['Nitro History', 'flash-outline', () => go('nitroHistory')]]],
 ['SECURITY & PRIVACY', [['Privacy Settings', 'shield-checkmark-outline', () => go('privacy')], ['Cookie & Storage Preferences', 'finger-print-outline', () => go('cookies')]]],
 ['SQUAD REFERRALS', [['Invite Squad', 'person-add-outline', () => go('inviteSquad')], ['My Saved Items', 'bookmark-outline', () => go('saved')], ['My Liked Items', 'heart-outline', () => go('liked')]]],
 ['SUPPORT', [['Ask NitroBot (AI Help)', 'hardware-chip-outline', () => go('help')], ['Send Query', 'chatbox-outline', () => go('feedback')]]],
 ['LEGAL', [['Privacy Policy', 'shield-outline', () => go('privacyPolicy')], ['Terms & Conditions', 'document-text-outline', () => go('terms')]]],
 ['ACCOUNT', [['Deactivate Account', 'person-remove-outline', () => setConfirm(true)], ['Log Out', 'log-out-outline', () => { setBusy(true); void authService.signOut().then(() => go('login')).catch(e => setError(e.message)).finally(() => setBusy(false)); }]]],
 ];
 return <Page><Header title="Settings" back={back} /><ScrollView contentContainerStyle={{ padding: 14, paddingBottom: 35 }}><ErrorLine text={error} /><Text style={[ui.section, { color: c.muted, marginTop: 13 }]}>APPEARANCE</Text><View style={{ padding: 16, backgroundColor: c.card, borderWidth: 1, borderColor: c.border, borderRadius: 16, gap: 17 }}><Text style={{ color: c.muted, fontSize: 10 }}>Choose how WeNitro looks on your device.</Text><View style={{ flexDirection: 'row', gap: 8 }}>{(['system', 'light', 'dark'] as const).map((choice, i) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: data.themePreference === choice }} key={choice} onPress={() => setData(current => ({ ...current, themePreference: choice, theme: choice === 'system' ? current.theme : choice }))} style={{ flex: 1, minHeight: 45, borderWidth: 1, borderColor: c.border, backgroundColor: data.themePreference === choice ? purple : c.bg, borderRadius: 12, flexDirection: 'row', gap: 7, alignItems: 'center', justifyContent: 'center' }}><Icon name={(['desktop-outline', 'sunny-outline', 'moon-outline'] as const)[i]} size={17} color={data.themePreference === choice ? '#FFF' : c.muted} /><Text style={{ fontSize: 12, fontWeight: '600', color: data.themePreference === choice ? '#FFF' : c.text }}>{choice[0].toUpperCase() + choice.slice(1)}</Text></Pressable>)}</View></View>
 {groups.map(([title, rows]) => <View key={title}><Text style={[ui.section, { color: c.muted }]}>{title}</Text><View style={{ backgroundColor: c.card, borderRadius: 13, paddingHorizontal: 14 }}>{rows.map(([label, icon, action], i) => <Pressable accessibilityRole="button" key={label} disabled={busy} onPress={action} style={{ flexDirection: 'row', alignItems: 'center', gap: 13, minHeight: 63 }}><View style={{ width: 34, height: 34, backgroundColor: c.bg + '60', borderRadius: 9, alignItems: 'center', justifyContent: 'center' }}><Icon name={icon as any} color={title === 'ACCOUNT' ? '#EE7180' : '#8474F8'} size={21} /></View><View style={{ flex: 1, minHeight: 63, justifyContent: 'center', borderBottomWidth: i === rows.length - 1 ? 0 : 1, borderColor: c.border }}><Text style={{ color: title === 'ACCOUNT' ? '#EF7C87' : c.text, fontSize: 13 }}>{label}</Text></View></Pressable>)}</View></View>)}
 <Text style={{ color: c.muted, fontSize: 10, textAlign: 'center', marginTop: 27 }}>WeNitro v{Constants.expoConfig?.version || '—'}</Text>
 </ScrollView>{confirm && <Sheet title="Deactivate Account?" centered close={() => { if (!busy) setConfirm(false); }}><Text style={{ color: c.muted, fontSize: 13, lineHeight: 21 }}>Your profile will be hidden and account access disabled. Your existing activities and messages will be retained. Contact support to request reactivation.</Text><Button label="Cancel" disabled={busy} onPress={() => setConfirm(false)} /><Button label="Deactivate" danger busy={busy} onPress={() => { setBusy(true); void Promise.resolve(supabase.rpc('deactivate_my_account', { p_confirmed: true })).then(async ({ error }) => { if (error) throw error; await authService.signOut(); go('login'); }).catch(e => setError(e.message)).finally(() => setBusy(false)); }} /></Sheet>}</Page>;
}
const audienceNames: Record<string, string> = { public: 'Everyone', friends: 'Squad Only', private: 'Private (None)', everyone: 'Everyone', none: 'No one' };
export function ReferencePrivacy({ back }: { back: () => void }) {
 const c = usePalette(); const [value, setValue] = useState<PrivacyPreferences | null>(null), [field, setField] = useState<'profile_visibility' | 'email_visibility' | 'phone_visibility' | 'message_visibility' | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''); const lock = useRef(false);
 useEffect(() => { let active = true; void profileProductionService.getPrivacyPreferences().then(v => { if (active) setValue(v); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, []);
 const save = async (patch: Partial<PrivacyPreferences>) => { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { const persisted = await profileProductionService.updatePrivacyPreferences(patch); setValue(persisted); setField(null); } catch (e: any) { setError(e.message); } finally { lock.current = false; setBusy(false); } };
 const choices = field === 'profile_visibility' ? ['public', 'friends', ...(value?.profile_visibility === 'private' ? ['private'] : [])] : field === 'message_visibility' ? ['everyone', 'friends', ...(value?.message_visibility === 'none' ? ['none'] : [])] : ['public', 'friends', 'private'];
 const labels = { profile_visibility: 'Profile Visibility', email_visibility: 'Email Visibility', phone_visibility: 'Phone Visibility', message_visibility: 'Messaging' };
 const row = (key: keyof typeof labels) => <Pressable key={key} accessibilityRole="button" disabled={busy} onPress={() => setField(key)} style={[ui.row, { backgroundColor: c.card, borderRadius: 11, marginBottom: 2, minHeight: 60 }]}><Text style={{ color: c.text, fontSize: 13, flex: 1 }}>{labels[key]}</Text><Text style={{ color: c.muted, fontSize: 12 }}>{key === 'profile_visibility' && value?.[key] === 'public' ? 'Public' : audienceNames[value?.[key] || 'private']}</Text><Icon name="chevron-forward" size={16} color={c.muted} /></Pressable>;
 return <Page><Header title="Privacy Settings" back={back} /><ErrorLine text={error} />{!value ? <Skeleton /> : <ScrollView contentContainerStyle={{ padding: 16 }}><Text style={[ui.section, { color: c.muted, marginTop: 12 }]}>PROFILE</Text>{row('profile_visibility')}<Text style={[ui.section, { color: c.muted }]}>CONTACT INFO</Text>{row('email_visibility')}{row('phone_visibility')}<Text style={[ui.section, { color: c.muted }]}>INTERACTIONS</Text>{row('message_visibility')}<Text style={[ui.section, { color: c.muted }]}>AVAILABILITY</Text><View style={[ui.row, { backgroundColor: c.card, borderRadius: 11 }]}><Text style={{ color: c.text, fontSize: 13, flex: 1 }}>Online Status</Text><Switch accessibilityLabel="Online Status" value={value.show_online_status} disabled={busy} onValueChange={v => void save({ show_online_status: v })} trackColor={{ true: purple, false: c.border }} /></View><Text style={{ color: c.muted, fontSize: 10, lineHeight: 17, paddingVertical: 20, textAlign: 'center' }}>Your privacy settings are saved to your account and sync across devices.</Text></ScrollView>}
 {field && value && <Sheet centered title={labels[field]} close={() => { if (!busy) setField(null); }}>{choices.map(option => <Pressable accessibilityRole="radio" accessibilityState={{ checked: value[field] === option }} disabled={busy} key={option} onPress={() => void save({ [field]: option })} style={{ padding: 14, borderRadius: 8, flexDirection: 'row', justifyContent: 'space-between', backgroundColor: value[field] === option ? '#6D5BED35' : 'transparent' }}><Text style={{ color: value[field] === option ? '#A496FF' : c.text, fontSize: 14 }}>{field === 'profile_visibility' && option === 'public' ? 'Public' : audienceNames[option]}</Text>{value[field] === option && <Icon name="checkmark" color="#A496FF" size={19} />}</Pressable>)}<ErrorLine text={error} /><Button label="Cancel" disabled={busy} onPress={() => setField(null)} /></Sheet>}
 </Page>;
}
export function ReferenceUtility({ screen, back, go }: { screen: Screen; back: () => void; go: (s: Screen) => void }) {
 const c = usePalette(); const [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [saved, setSaved] = useState(false); const lock = useRef(false);
 const title = screen === 'cookies' ? 'Cookie & Storage Preferences' : screen === 'help' ? 'Ask NitroBot (AI Help)' : screen === 'feedback' ? 'Send Query' : screen === 'privacyPolicy' ? 'Privacy Policy' : 'Terms & Conditions';
 return <Page><Header title={title} back={back} /><ScrollView contentContainerStyle={{ padding: 20, gap: 18 }}>
 {screen === 'cookies' ? <><Text style={{ color: c.text, fontSize: 16, fontWeight: '600' }}>Essential storage</Text><Text style={{ color: c.muted, fontSize: 13, lineHeight: 21 }}>Authentication, security, onboarding and appearance preferences use essential storage. Optional analytics, personalization and marketing cookies are not enabled.</Text><Text style={{ color: c.muted, fontSize: 13, lineHeight: 21 }}>Logging out removes your session. Your account data and saved items remain in your account.</Text></> : screen === 'help' ? <><Icon name="hardware-chip-outline" color={purple} size={42} /><Text style={{ color: c.text, fontSize: 17, fontWeight: '600' }}>How can we help?</Text><Text style={{ color: c.muted, fontSize: 13, lineHeight: 21 }}>NitroBot is not connected yet. You can send a query to the WeNitro team about your account, activities, or a safety concern.</Text><Button label="Send Query" onPress={() => go('feedback')} /></> : screen === 'feedback' ? <><Text style={{ color: c.muted, fontSize: 13, lineHeight: 21 }}>Tell us about your question or issue.</Text><Field multiline accessibilityLabel="Your query" placeholder="Write your query..." value={message} onChangeText={setMessage} maxLength={4000} editable={!busy && !saved} style={{ minHeight: 145, textAlignVertical: 'top' }} /><ErrorLine text={error} />{saved ? <Text style={{ color: '#51B979', fontSize: 13 }}>Your query has been submitted.</Text> : <Button label="Send Query" busy={busy} disabled={message.trim().length < 10} onPress={() => { if (lock.current) return; lock.current = true; setBusy(true); void Promise.resolve(supabase.rpc('submit_support_query', { p_message: message.trim() })).then(({ error }) => { if (error) throw error; setSaved(true); }).catch(e => setError(e.message)).finally(() => { lock.current = false; setBusy(false); }); }} />}</> : <Text style={{ color: c.muted, fontSize: 13, lineHeight: 21 }}>{title} content will be displayed here soon.</Text>}
 </ScrollView></Page>;
}
export function ReferenceStore({ points, back }: { points: number; back: () => void }) {
 const c = usePalette(); const [balance, setBalance] = useState<number | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(''), [toast, setToast] = useState('');
 const lock = useRef(false), mounted = useRef(true);
 const check = async () => {
  if (lock.current) return; lock.current = true; setLoading(true); setError(''); setToast('');
  try { const result = await supabase.rpc('my_profile_metrics'); if (result.error) throw result.error; const current = Number(result.data?.nitro); if (!Number.isFinite(current)) throw new Error('Could not check your Nitro balance.'); if (mounted.current) { setBalance(current); if (!storeEligible(current)) setToast(`Minimum 500 Nitro Points required to shop. You currently have ${current} points.`); } }
  catch (e: any) { if (mounted.current) setError(e?.message || 'Could not load the store.'); }
  finally { lock.current = false; if (mounted.current) setLoading(false); }
 };
 useEffect(() => { mounted.current = true; void check(); return () => { mounted.current = false; }; }, []);
 useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 6000); return () => clearTimeout(timer); }, [toast]);
 const gated = balance !== null && !storeEligible(balance);
 return <Page><Header title="Nitro Store" back={back} />{toast && <View accessibilityRole="alert" style={{ backgroundColor: '#B82E46', margin: 14, padding: 14, borderRadius: 10 }}><Text style={{ color: '#FFF', fontSize: 12, lineHeight: 19 }}>{toast}</Text></View>}{loading ? <Skeleton /> : <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center', padding: 30, gap: 20 }}><Icon name={gated || error ? 'alert-circle-outline' : 'lock-closed-outline'} size={49} color={gated || error ? '#F47786' : purple} /><Text style={{ color: c.text, fontSize: 23, fontWeight: '700', textAlign: 'center' }}>{gated || error ? 'Unable to Load Store' : 'FEATURE UNLOCKS SOON'}</Text><Text style={{ color: c.muted, fontSize: 13, lineHeight: 22, textAlign: 'center' }}>{error || (gated ? `Minimum 500 Nitro Points required to shop. You currently have ${balance} points.` : `You have ${balance} Nitro points. The store is coming soon.`)}</Text><View style={{ minWidth: 120 }}><Button label="Retry" onPress={() => void check()} /></View></View>}</Page>;
}
