begin;

create table if not exists public.tbl_activity_payments (
  id bigint generated by default as identity primary key,
  event_id integer not null references public.tbl_events(id) on delete restrict,
  user_id integer not null references public.tbl_users(id) on delete restrict,
  provider text not null default 'cashfree'
    check (provider = 'cashfree'),
  provider_order_id text not null unique,
  provider_payment_id text,
  payment_session_id text,
  amount_paisa bigint not null check (amount_paisa > 0),
  currency text not null default 'INR'
    check (currency = 'INR'),
  status text not null default 'created'
    check (status in ('created', 'pending', 'paid', 'failed', 'cancelled', 'expired')),
  provider_status text,
  idempotency_key uuid not null default gen_random_uuid() unique,
  checkout_expires_at timestamptz not null default (now() + interval '20 minutes'),
  paid_at timestamptz,
  last_verified_at timestamptz,
  provider_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists activity_payments_event_idx
  on public.tbl_activity_payments(event_id, created_at desc);
create index if not exists activity_payments_user_idx
  on public.tbl_activity_payments(user_id, created_at desc);
create unique index if not exists activity_payments_one_open_attempt_idx
  on public.tbl_activity_payments(event_id, user_id)
  where status in ('created', 'pending');

alter table public.tbl_activity_payments enable row level security;
revoke all on table public.tbl_activity_payments from public, anon, authenticated;
grant select on table public.tbl_activity_payments to authenticated;
revoke all on sequence public.tbl_activity_payments_id_seq from public, anon, authenticated;

drop policy if exists activity_payments_owner_read on public.tbl_activity_payments;
create policy activity_payments_owner_read
  on public.tbl_activity_payments
  for select
  to authenticated
  using (
    user_id = public.get_current_app_user_id()
    or public.is_wenitro_admin()
  );

create or replace function public.prepare_activity_payment(p_event_id integer)
returns public.tbl_activity_payments
language plpgsql
security definer
set search_path = public
as $function$
declare
  me integer := public.get_current_app_user_id();
  event_row public.tbl_events;
  participation public.tbl_event_participants;
  payment public.tbl_activity_payments;
  amount_minor bigint;
  occupied integer;
  generated_order_id text;
begin
  if me is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select *
    into event_row
    from public.tbl_events
    where id = p_event_id
      and status = 'published'
      and not coalesce(is_deleted, false)
      and not coalesce(is_cancelled, false)
    for update;

  if event_row.id is null then
    raise exception 'Activity is unavailable';
  end if;
  if event_row.created_by = me then
    raise exception 'Hosts cannot pay to join their own activity';
  end if;
  if event_row.registration_close_time is not null
     and event_row.registration_close_time < now() then
    raise exception 'Registration is closed';
  end if;
  if not coalesce(event_row.is_paid, false)
     or coalesce(event_row.price, 0) <= 0 then
    raise exception 'This activity does not require payment';
  end if;
  if coalesce(event_row.currency, 'INR') <> 'INR' then
    raise exception 'Only INR activities are supported';
  end if;

  amount_minor := round(event_row.price * 100)::bigint;
  if amount_minor <= 0 or abs(event_row.price * 100 - amount_minor) > 0.000001 then
    raise exception 'Activity price must have at most two decimal places';
  end if;

  select *
    into participation
    from public.tbl_event_participants
    where event_id = p_event_id and user_id = me
    for update;

  if participation.status in ('approved', 'going') then
    raise exception 'You have already joined this activity';
  end if;
  if event_row.join_type = 'approval'
     and coalesce(participation.status, '') <> 'payment_required' then
    raise exception 'Host approval is required before payment';
  end if;

  update public.tbl_activity_payments
    set status = 'expired',
        provider_status = coalesce(provider_status, 'LOCAL_EXPIRED'),
        updated_at = now()
    where event_id = p_event_id
      and user_id = me
      and status in ('created', 'pending')
      and checkout_expires_at <= now();

  select *
    into payment
    from public.tbl_activity_payments
    where event_id = p_event_id
      and user_id = me
      and status in ('created', 'pending')
      and checkout_expires_at > now()
    order by created_at desc
    limit 1
    for update;

  if payment.id is not null then
    if payment.amount_paisa <> amount_minor or payment.currency <> 'INR' then
      raise exception 'The activity price changed; start a new payment attempt';
    end if;
    return payment;
  end if;

  select count(*)
    into occupied
    from public.tbl_event_participants
    where event_id = p_event_id
      and user_id <> me
      and status in ('approved', 'going', 'payment_required');

  if event_row.max_participants is not null
     and occupied >= event_row.max_participants then
    raise exception 'Activity is full';
  end if;

  if event_row.join_type <> 'approval' then
    insert into public.tbl_event_participants(
      event_id, user_id, status, responded_at, joined_at
    )
    values (p_event_id, me, 'payment_required', null, null)
    on conflict(event_id, user_id) do update
      set status = case
        when tbl_event_participants.status in ('approved', 'going')
          then tbl_event_participants.status
        else 'payment_required'
      end,
      responded_at = null,
      joined_at = null
    returning * into participation;
  end if;

  generated_order_id :=
    'wn_' || p_event_id::text || '_' || me::text || '_' ||
    substr(replace(gen_random_uuid()::text, '-', ''), 1, 20);

  insert into public.tbl_activity_payments(
    event_id,
    user_id,
    provider_order_id,
    amount_paisa,
    currency,
    status,
    checkout_expires_at
  )
  values (
    p_event_id,
    me,
    generated_order_id,
    amount_minor,
    'INR',
    'created',
    now() + interval '20 minutes'
  )
  returning * into payment;

  return payment;
end
$function$;

create or replace function public.record_cashfree_order(
  p_order_id text,
  p_payment_session_id text,
  p_provider_status text,
  p_checkout_expires_at timestamptz,
  p_provider_metadata jsonb default '{}'::jsonb
)
returns public.tbl_activity_payments
language plpgsql
security definer
set search_path = public
as $function$
declare
  payment public.tbl_activity_payments;
begin
  update public.tbl_activity_payments
    set payment_session_id = p_payment_session_id,
        provider_status = nullif(p_provider_status, ''),
        status = case when status = 'paid' then status else 'pending' end,
        checkout_expires_at = coalesce(p_checkout_expires_at, checkout_expires_at),
        provider_metadata = coalesce(provider_metadata, '{}'::jsonb)
          || coalesce(p_provider_metadata, '{}'::jsonb),
        updated_at = now()
    where provider_order_id = p_order_id
    returning * into payment;

  if payment.id is null then
    raise exception 'Payment order not found';
  end if;
  return payment;
end
$function$;

create or replace function public.record_activity_payment_provider_state(
  p_order_id text,
  p_status text,
  p_provider_status text,
  p_provider_payment_id text default null,
  p_provider_metadata jsonb default '{}'::jsonb
)
returns public.tbl_activity_payments
language plpgsql
security definer
set search_path = public
as $function$
declare
  normalized_status text;
  payment public.tbl_activity_payments;
begin
  normalized_status := case
    when p_status in ('created', 'pending', 'failed', 'cancelled', 'expired')
      then p_status
    else 'pending'
  end;

  update public.tbl_activity_payments
    set status = case when status = 'paid' then status else normalized_status end,
        provider_status = nullif(p_provider_status, ''),
        provider_payment_id = coalesce(
          nullif(p_provider_payment_id, ''),
          provider_payment_id
        ),
        provider_metadata = coalesce(provider_metadata, '{}'::jsonb)
          || coalesce(p_provider_metadata, '{}'::jsonb),
        last_verified_at = now(),
        updated_at = now()
    where provider_order_id = p_order_id
    returning * into payment;

  return payment;
end
$function$;

create or replace function public.finalize_activity_payment(
  p_order_id text,
  p_provider_payment_id text,
  p_amount_paisa bigint,
  p_currency text,
  p_provider_status text,
  p_provider_metadata jsonb default '{}'::jsonb
)
returns public.tbl_activity_payments
language plpgsql
security definer
set search_path = public
as $function$
declare
  payment public.tbl_activity_payments;
  event_row public.tbl_events;
  occupied integer;
begin
  select *
    into payment
    from public.tbl_activity_payments
    where provider_order_id = p_order_id
    for update;

  if payment.id is null then
    raise exception 'Payment order not found';
  end if;
  if payment.status = 'paid' then
    return payment;
  end if;
  if p_provider_status not in ('PAID', 'SUCCESS') then
    raise exception 'Provider has not confirmed payment';
  end if;
  if payment.amount_paisa <> p_amount_paisa or payment.currency <> p_currency then
    raise exception 'Provider payment amount does not match the server ledger';
  end if;

  select *
    into event_row
    from public.tbl_events
    where id = payment.event_id
      and not coalesce(is_deleted, false)
      and not coalesce(is_cancelled, false)
    for update;

  if event_row.id is null then
    raise exception 'Activity is unavailable';
  end if;

  select count(*)
    into occupied
    from public.tbl_event_participants
    where event_id = payment.event_id
      and user_id <> payment.user_id
      and status in ('approved', 'going');

  if event_row.max_participants is not null
     and occupied >= event_row.max_participants then
    raise exception 'Reserved activity capacity is no longer available';
  end if;

  insert into public.tbl_event_participants(
    event_id, user_id, status, responded_at, joined_at
  )
  values (
    payment.event_id,
    payment.user_id,
    'approved',
    now(),
    now()
  )
  on conflict(event_id, user_id) do update
    set status = 'approved',
        responded_at = now(),
        joined_at = coalesce(tbl_event_participants.joined_at, now());

  update public.tbl_activity_payments
    set status = 'paid',
        provider_status = p_provider_status,
        provider_payment_id = coalesce(
          nullif(p_provider_payment_id, ''),
          provider_payment_id
        ),
        provider_metadata = coalesce(provider_metadata, '{}'::jsonb)
          || coalesce(p_provider_metadata, '{}'::jsonb),
        paid_at = coalesce(paid_at, now()),
        last_verified_at = now(),
        updated_at = now()
    where id = payment.id
    returning * into payment;

  return payment;
end
$function$;

create or replace function public.request_join_activity(
  p_event_id integer,
  p_status text default 'going'
)
returns public.tbl_event_participants
language plpgsql
security definer
set search_path = public
as $function$
declare
  me integer := public.get_current_app_user_id();
  event_row public.tbl_events;
  db_status text;
  result_row public.tbl_event_participants;
  occupied integer;
begin
  select *
    into event_row
    from public.tbl_events
    where id = p_event_id
      and not coalesce(is_deleted, false)
      and not coalesce(is_cancelled, false)
    for update;

  if event_row.id is null then
    raise exception 'Activity is unavailable';
  end if;
  if event_row.created_by = me then
    raise exception 'Hosts cannot join their own activity';
  end if;
  if event_row.registration_close_time is not null
     and event_row.registration_close_time < now()
     and p_status not in ('left', 'declined') then
    raise exception 'Registration is closed';
  end if;
  if p_status not in ('going', 'interested', 'waitlist', 'left', 'declined') then
    raise exception 'Invalid participation status';
  end if;

  select count(*)
    into occupied
    from public.tbl_event_participants
    where event_id = p_event_id
      and user_id <> me
      and status in ('approved', 'going', 'payment_required');

  db_status := case
    when p_status in ('left', 'declined') then 'left'
    when p_status in ('interested', 'waitlist') then 'pending'
    when coalesce(event_row.is_paid, false)
         and event_row.join_type = 'direct'
         and (event_row.max_participants is null or occupied < event_row.max_participants)
      then 'payment_required'
    when event_row.join_type = 'direct'
         and (event_row.max_participants is null or occupied < event_row.max_participants)
      then 'approved'
    else 'pending'
  end;

  insert into public.tbl_event_participants(
    event_id, user_id, status, responded_at, joined_at
  )
  values (
    p_event_id,
    me,
    db_status,
    case when db_status in ('approved', 'rejected') then now() end,
    case when db_status = 'approved' then now() end
  )
  on conflict(event_id, user_id) do update
    set status = excluded.status,
        responded_at = excluded.responded_at,
        joined_at = excluded.joined_at
  returning * into result_row;

  return result_row;
end
$function$;

create or replace function public.respond_activity_join(
  p_event_id integer,
  p_user_id integer,
  p_status text
)
returns public.tbl_event_participants
language plpgsql
security definer
set search_path = public
as $function$
declare
  me integer := public.get_current_app_user_id();
  event_row public.tbl_events;
  normalized_status text;
  result_row public.tbl_event_participants;
  occupied integer;
begin
  select *
    into event_row
    from public.tbl_events
    where id = p_event_id and created_by = me
    for update;

  if event_row.id is null then
    raise exception 'Only the host can respond' using errcode = '42501';
  end if;
  if p_status not in ('approved', 'rejected', 'waitlist') then
    raise exception 'Invalid response';
  end if;

  normalized_status := case
    when p_status = 'waitlist' then 'pending'
    when p_status = 'approved' and coalesce(event_row.is_paid, false)
      then 'payment_required'
    else p_status
  end;

  if normalized_status in ('approved', 'payment_required')
     and event_row.max_participants is not null then
    select count(*)
      into occupied
      from public.tbl_event_participants
      where event_id = p_event_id
        and user_id <> p_user_id
        and status in ('approved', 'going', 'payment_required');
    if occupied >= event_row.max_participants then
      raise exception 'Activity is full';
    end if;
  end if;

  update public.tbl_event_participants
    set status = normalized_status,
        responded_at = now(),
        joined_at = case
          when normalized_status = 'approved' then coalesce(joined_at, now())
          else null
        end
    where event_id = p_event_id and user_id = p_user_id
    returning * into result_row;

  if result_row.id is null then
    raise exception 'Join request not found';
  end if;
  return result_row;
end
$function$;

revoke all on function public.prepare_activity_payment(integer)
  from public, anon;
grant execute on function public.prepare_activity_payment(integer)
  to authenticated, service_role;

revoke all on function public.record_cashfree_order(
  text, text, text, timestamptz, jsonb
) from public, anon, authenticated;
grant execute on function public.record_cashfree_order(
  text, text, text, timestamptz, jsonb
) to service_role;

revoke all on function public.record_activity_payment_provider_state(
  text, text, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.record_activity_payment_provider_state(
  text, text, text, text, jsonb
) to service_role;

revoke all on function public.finalize_activity_payment(
  text, text, bigint, text, text, jsonb
) from public, anon, authenticated;
grant execute on function public.finalize_activity_payment(
  text, text, bigint, text, text, jsonb
) to service_role;

revoke all on function public.request_join_activity(integer, text)
  from public, anon;
grant execute on function public.request_join_activity(integer, text)
  to authenticated, service_role;
revoke all on function public.respond_activity_join(integer, integer, text)
  from public, anon;
grant execute on function public.respond_activity_join(integer, integer, text)
  to authenticated, service_role;

commit;
