-- Reference delta: private profile utilities and host participant ratings.
-- Every callable function derives the legacy user id from the authenticated
-- Supabase identity. Aadhaar verification is intentionally out of scope until
-- a real provider is connected.

alter table public.tbl_participant_ratings
  add column if not exists behaviour_rating integer,
  add column if not exists friendly_rating integer,
  add column if not exists communication_rating integer;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tbl_participant_ratings_behaviour_check') then
    alter table public.tbl_participant_ratings add constraint tbl_participant_ratings_behaviour_check check (behaviour_rating between 1 and 5);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tbl_participant_ratings_friendly_check') then
    alter table public.tbl_participant_ratings add constraint tbl_participant_ratings_friendly_check check (friendly_rating between 1 and 5);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'tbl_participant_ratings_communication_check') then
    alter table public.tbl_participant_ratings add constraint tbl_participant_ratings_communication_check check (communication_rating between 1 and 5);
  end if;
end
$$;

create table if not exists public.tbl_user_profile_photos (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.tbl_users(id) on delete cascade,
  storage_path text not null,
  public_url text not null,
  position integer not null check (position between 2 and 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, position),
  unique (user_id, storage_path)
);

alter table public.tbl_user_profile_photos enable row level security;
drop policy if exists own_profile_photos_read on public.tbl_user_profile_photos;
create policy own_profile_photos_read on public.tbl_user_profile_photos for select to authenticated
  using (user_id = public.get_current_app_user_id());
drop policy if exists own_profile_photos_insert on public.tbl_user_profile_photos;
create policy own_profile_photos_insert on public.tbl_user_profile_photos for insert to authenticated
  with check (user_id = public.get_current_app_user_id());
drop policy if exists own_profile_photos_update on public.tbl_user_profile_photos;
create policy own_profile_photos_update on public.tbl_user_profile_photos for update to authenticated
  using (user_id = public.get_current_app_user_id())
  with check (user_id = public.get_current_app_user_id());
drop policy if exists own_profile_photos_delete on public.tbl_user_profile_photos;
create policy own_profile_photos_delete on public.tbl_user_profile_photos for delete to authenticated
  using (user_id = public.get_current_app_user_id());

grant select, insert, update, delete on public.tbl_user_profile_photos to authenticated;
grant usage, select on sequence public.tbl_user_profile_photos_id_seq to authenticated;

create or replace function public.get_my_emergency_contact()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select jsonb_build_object(
      'id', c.id,
      'contact_name', c.contact_name,
      'relation', c.relation,
      'countrycode', c.countrycode,
      'phone_number', c.phone_number,
      'is_verified', c.is_verified,
      'updated_at', c.updated_at
    ) from public.tbl_emergency_contacts c
      where c.user_id = public.get_current_app_user_id()),
    '{}'::jsonb
  )
$$;

create or replace function public.save_my_emergency_contact(
  p_contact_name text,
  p_relation text,
  p_phone_number text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  me integer := public.get_current_app_user_id();
  clean_name text := btrim(coalesce(p_contact_name, ''));
  clean_phone text := regexp_replace(coalesce(p_phone_number, ''), '[^0-9]', '', 'g');
  row public.tbl_emergency_contacts;
begin
  if length(clean_name) not between 2 and 100 then raise exception 'Contact name must contain 2 to 100 characters'; end if;
  if p_relation not in ('Parent','Spouse','Sibling','Friend','Partner','Guardian','Other') then raise exception 'Choose a valid relation'; end if;
  if clean_phone !~ '^[6-9][0-9]{9}$' then raise exception 'Enter a valid 10-digit Indian mobile number'; end if;

  insert into public.tbl_emergency_contacts(user_id, contact_name, relation, countrycode, phone_number, is_verified, updated_at)
  values(me, clean_name, p_relation, '+91', clean_phone, false, now())
  on conflict(user_id) do update set
    contact_name = excluded.contact_name,
    relation = excluded.relation,
    countrycode = excluded.countrycode,
    phone_number = excluded.phone_number,
    is_verified = case when public.tbl_emergency_contacts.phone_number = excluded.phone_number then public.tbl_emergency_contacts.is_verified else false end,
    updated_at = now()
  returning * into row;

  return jsonb_build_object('id',row.id,'contact_name',row.contact_name,'relation',row.relation,'countrycode',row.countrycode,'phone_number',row.phone_number,'is_verified',row.is_verified,'updated_at',row.updated_at);
end
$$;

create or replace function public.list_my_squad()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with me as (select public.get_current_app_user_id() id),
  related as (
    select case when f.user_id = me.id then f.friend_id else f.user_id end member_id,
           f.created_at
    from public.tbl_friends f cross join me
    where f.user_id = me.id or f.friend_id = me.id
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',u.id,'username',u.username,'fullname',u.fullname,
    'profile_image',u.profile_image,'isverified',u.isverified,'connected_at',r.created_at
  ) order by coalesce(u.fullname,u.username),u.id), '[]'::jsonb)
  from related r join public.tbl_users u on u.id=r.member_id
  where coalesce(u.is_delete,0)=0 and coalesce(u.is_active,1)=1
$$;

create or replace function public.remove_my_squad_member(p_member_id integer)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare me integer := public.get_current_app_user_id();
begin
  if p_member_id is null or p_member_id = me then raise exception 'Invalid Squad member'; end if;
  delete from public.tbl_friends f
  where (f.user_id=me and f.friend_id=p_member_id)
     or (f.friend_id=me and f.user_id=p_member_id);
  if not found then raise exception 'Squad member not found'; end if;
end
$$;

create or replace function public.list_my_nitro_history()
returns jsonb
language sql
stable
security definer
set search_path = ''
as $$
  with me as (select public.get_current_app_user_id() id),
  entries as (
    select h.id,h.points_earned,h.created_at,r.event_id,e.title
    from public.tbl_user_points_history h
    join me on me.id=h.user_id
    left join public.tbl_participant_ratings r on r.id=h.rating_id
    left join public.tbl_events e on e.id=r.event_id
    order by h.created_at desc,h.id desc
  )
  select jsonb_build_object(
    'balance',(select coalesce(u.points,0) from public.tbl_users u join me on me.id=u.id),
    'items',coalesce((select jsonb_agg(jsonb_build_object(
      'id',id,'points',points_earned,'created_at',created_at,'event_id',event_id,
      'description',case when title is null then 'Activity participation rating' else 'Rating for '||title end
    ) order by created_at desc,id desc) from entries),'[]'::jsonb)
  )
$$;

create or replace function public.list_activity_participant_ratings(p_event_id integer)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare me integer := public.get_current_app_user_id(); result jsonb;
begin
  if not exists(select 1 from public.tbl_events e where e.id=p_event_id and (e.created_by=me or exists(select 1 from public.tbl_event_participants p where p.event_id=e.id and p.user_id=me))) then
    raise exception 'Activity ratings are unavailable' using errcode='42501';
  end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',r.id,'rated_user_id',r.rated_user_id,'behaviour_rating',r.behaviour_rating,
    'friendly_rating',r.friendly_rating,'communication_rating',r.communication_rating,
    'overall_rating',r.overall_rating,'comment',coalesce(r.comment,''),'updated_at',r.updated_at
  ) order by r.updated_at desc),'[]'::jsonb) into result
  from public.tbl_participant_ratings r where r.event_id=p_event_id and (r.rater_id=me or r.rated_user_id=me);
  return result;
end
$$;

create or replace function public.rate_activity_participant(
  p_event_id integer,
  p_user_id integer,
  p_behaviour integer,
  p_friendly integer,
  p_communication integer,
  p_comment text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  me integer := public.get_current_app_user_id();
  overall integer;
  row public.tbl_participant_ratings;
begin
  if not exists(select 1 from public.tbl_events e where e.id=p_event_id and e.created_by=me and (e.status='completed' or e.event_end_time<=now())) then
    raise exception 'Only the host can rate participants after the Activity ends' using errcode='42501';
  end if;
  if not exists(select 1 from public.tbl_event_participants p where p.event_id=p_event_id and p.user_id=p_user_id and p.status in ('approved','no_show')) then
    raise exception 'This member is not an approved participant';
  end if;
  if p_behaviour not between 1 and 5 or p_friendly not between 1 and 5 or p_communication not between 1 and 5 then
    raise exception 'Choose 1 to 5 stars for every rating';
  end if;
  if length(btrim(coalesce(p_comment,''))) > 1000 then raise exception 'Feedback must be 1000 characters or fewer'; end if;
  overall := round((p_behaviour+p_friendly+p_communication)::numeric/3)::integer;
  insert into public.tbl_participant_ratings(event_id,rater_id,rated_user_id,overall_rating,behaviour_rating,friendly_rating,communication_rating,comment,is_no_show,updated_at)
  values(p_event_id,me,p_user_id,overall,p_behaviour,p_friendly,p_communication,nullif(btrim(coalesce(p_comment,'')),''),false,now())
  on conflict(event_id,rater_id,rated_user_id) do update set
    overall_rating=excluded.overall_rating,behaviour_rating=excluded.behaviour_rating,
    friendly_rating=excluded.friendly_rating,communication_rating=excluded.communication_rating,
    comment=excluded.comment,is_no_show=false,updated_at=now()
  returning * into row;

  update public.tbl_users u set rating=(select round(avg(r.overall_rating)::numeric,2) from public.tbl_participant_ratings r where r.rated_user_id=p_user_id and not coalesce(r.is_no_show,false)) where u.id=p_user_id;
  return jsonb_build_object('id',row.id,'rated_user_id',row.rated_user_id,'behaviour_rating',row.behaviour_rating,'friendly_rating',row.friendly_rating,'communication_rating',row.communication_rating,'overall_rating',row.overall_rating,'comment',coalesce(row.comment,''),'updated_at',row.updated_at);
end
$$;

create or replace function public.sync_my_phone_verification()
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  me integer := public.get_current_app_user_id();
  auth_phone text;
  confirmed timestamptz;
  verification_id integer;
begin
  select u.phone,u.phone_confirmed_at into auth_phone,confirmed from auth.users u where u.id=auth.uid();
  if auth_phone is null or confirmed is null then raise exception 'Phone verification is not complete'; end if;
  if auth_phone !~ '^\+91[6-9][0-9]{9}$' then raise exception 'Only verified Indian mobile numbers are supported'; end if;
  update public.tbl_users set phone_e164=auth_phone,countrycode='+91',phonenumber=substring(auth_phone from 4)::bigint where id=me;
  select v.id into verification_id from public.tbl_user_verification v where v.user_id=me order by v.created_at desc,v.id desc limit 1;
  if verification_id is null then
    insert into public.tbl_user_verification(user_id,phone_verified,aadhaar_verified,verification_type,status) values(me,true,false,'identity','draft') returning id into verification_id;
  else
    update public.tbl_user_verification set phone_verified=true,updated_at=now() where id=verification_id;
  end if;
  return jsonb_build_object('phone',auth_phone,'phone_verified',true,'verification_id',verification_id);
end
$$;

revoke all on function public.get_my_emergency_contact(),public.save_my_emergency_contact(text,text,text),public.list_my_squad(),public.remove_my_squad_member(integer),public.list_my_nitro_history(),public.list_activity_participant_ratings(integer),public.rate_activity_participant(integer,integer,integer,integer,integer,text),public.sync_my_phone_verification() from public,anon;
grant execute on function public.get_my_emergency_contact(),public.save_my_emergency_contact(text,text,text),public.list_my_squad(),public.remove_my_squad_member(integer),public.list_my_nitro_history(),public.list_activity_participant_ratings(integer),public.rate_activity_participant(integer,integer,integer,integer,integer,text),public.sync_my_phone_verification() to authenticated;
