create or replace function private.community_counts(p_room_ids integer[]) returns jsonb language sql stable security definer set search_path='' as $$ select coalesce(jsonb_object_agg(r.id,(select count(*) from public.tbl_chat_participants where room_id=r.id)),'{}'::jsonb) from public.tbl_chat_rooms r where auth.uid() is not null and r.id=any(p_room_ids[1:50]) and r.room_type='community' and (r.visibility='public' or public.is_chat_member(r.id)) $$;
create or replace function public.community_counts(p_room_ids integer[]) returns jsonb language sql security invoker set search_path='' as $$ select private.community_counts(p_room_ids) $$;
create or replace function private.my_profile_metrics() returns jsonb language plpgsql stable security definer set search_path='' as $$
 declare me integer:=public.get_current_app_user_id(); u public.tbl_users;
 begin select * into u from public.tbl_users where id=me;
 return jsonb_build_object('verified',u.isverified=1,'nitro',coalesce(u.points,0),'karma',0,'trust_score',null,'rating',coalesce(u.rating,0),'activities',(select count(*) from public.tbl_events e where not coalesce(e.is_deleted,false) and not coalesce(e.is_cancelled,false) and e.status<>'draft' and (e.created_by=me or exists(select 1 from public.tbl_event_participants p where p.event_id=e.id and p.user_id=me and p.status in ('going','approved')))),'squad',(select count(distinct case when f.user_id=me then f.friend_id else f.user_id end) from public.tbl_friends f where f.user_id=me or f.friend_id=me),'phone_verified',exists(select 1 from auth.users where id=auth.uid() and phone_confirmed_at is not null) or exists(select 1 from public.tbl_user_verification where user_id=me and phone_verified),'aadhaar_verified',exists(select 1 from public.tbl_user_verification where user_id=me and aadhaar_verified and status='approved'),'social_linked',exists(select 1 from public.tbl_user_social_links where user_id=me and coalesce(nullif(instagram,''),nullif(facebook,''),nullif(twitter,''),nullif(linkedin,''),nullif(youtube,'')) is not null));
 end;
$$;
create or replace function public.my_profile_metrics() returns jsonb language sql security invoker set search_path='' as $$ select private.my_profile_metrics() $$;
create or replace function private.submit_support_query(p_message text) returns integer language plpgsql security definer set search_path='' as $$ declare me integer:=public.get_current_app_user_id(); result integer; begin if length(trim(p_message)) not between 10 and 4000 then raise exception 'Query must be 10 to 4000 characters'; end if; perform pg_advisory_xact_lock(hashtextextended(me::text||p_message,0)); select id into result from public.tbl_user_feedbacks where user_id=me and message=trim(p_message) and created_at>now()-interval '1 minute' order by id desc limit 1; if result is null then insert into public.tbl_user_feedbacks(user_id,type,message) values(me,'other',trim(p_message)) returning id into result; end if; return result; end $$;
create or replace function public.submit_support_query(p_message text) returns integer language sql security invoker set search_path='' as $$ select private.submit_support_query(p_message) $$;
-- Safe social URL editing reuses the existing per-user row; no verification claim.
create or replace function private.my_social_links(p_patch jsonb default null) returns jsonb language plpgsql security definer set search_path='' as $$ declare me integer:=public.get_current_app_user_id(); k text; v text; begin if p_patch is not null then for k,v in select * from jsonb_each_text(p_patch) loop if k not in ('instagram','linkedin','facebook','twitter','youtube') or length(v)>250 or (v<>'' and v !~ '^https://[^ /]+(/.*)?$') then raise exception 'Use a valid https social profile URL'; end if; end loop; insert into public.tbl_user_social_links(user_id) values(me) on conflict(user_id) do nothing; update public.tbl_user_social_links set instagram=case when p_patch?'instagram' then nullif(p_patch->>'instagram','') else instagram end,linkedin=case when p_patch?'linkedin' then nullif(p_patch->>'linkedin','') else linkedin end,facebook=case when p_patch?'facebook' then nullif(p_patch->>'facebook','') else facebook end,twitter=case when p_patch?'twitter' then nullif(p_patch->>'twitter','') else twitter end,youtube=case when p_patch?'youtube' then nullif(p_patch->>'youtube','') else youtube end,updated_at=now() where user_id=me; end if; return coalesce((select jsonb_build_object('instagram',instagram,'linkedin',linkedin,'facebook',facebook,'twitter',twitter,'youtube',youtube) from public.tbl_user_social_links where user_id=me),'{}'::jsonb); end $$;
create or replace function public.my_social_links(p_patch jsonb default null) returns jsonb language sql security invoker set search_path='' as $$ select private.my_social_links(p_patch) $$;
do $$ declare f record; begin for f in select p.oid::regprocedure signature from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('private','public') and p.proname in ('community_counts','my_profile_metrics','submit_support_query','my_social_links') loop execute format('revoke all on function %s from public,anon,authenticated',f.signature); execute format('grant execute on function %s to authenticated',f.signature); end loop; end $$;
