-- Community and vibe bridge used by the production mobile services.
alter table public.tbl_chat_rooms add column if not exists tagline text,add column if not exists tags text[] not null default '{}',add column if not exists rules text[] not null default '{}',add column if not exists visibility varchar(20) not null default 'public',add column if not exists cover_url text;
alter table public.tbl_community_post_comments add column if not exists parent_id bigint references public.tbl_community_post_comments(id) on delete cascade;
alter table public.tbl_activity_vibes add column if not exists caption text not null default '',add column if not exists hashtags text[] not null default '{}',add column if not exists visibility varchar(20) not null default 'public',add column if not exists updated_at timestamptz not null default now();
alter table public.tbl_vibe_comments add column if not exists parent_id integer references public.tbl_vibe_comments(id) on delete cascade,add column if not exists updated_at timestamptz not null default now();
create table if not exists public.tbl_vibe_shares(id bigserial primary key,vibe_id bigint not null references public.tbl_activity_vibes(id) on delete cascade,user_id integer not null references public.tbl_users(id) on delete cascade,channel varchar(30) not null,created_at timestamptz not null default now());
create or replace function public.get_current_legacy_user_id() returns integer language sql stable security definer set search_path=public as $$ select public.get_current_app_user_id() $$;

create or replace function public.community_create(p_name text,p_tagline text,p_description text,p_category text,p_tags text[],p_rules text[],p_image_path text,p_cover_path text,p_visibility text) returns integer language plpgsql security definer set search_path=public as $$
declare me integer:=public.get_current_app_user_id(); rid integer; cid integer;
begin
 if length(trim(p_name)) not between 3 and 100 then raise exception 'Invalid community name'; end if; if p_visibility not in ('public','private') then raise exception 'Invalid visibility'; end if;
 if nullif(trim(p_category),'') is not null then select id into cid from public.tbl_categories where lower(name)=lower(trim(p_category)) order by id limit 1; if cid is null then insert into public.tbl_categories(name) values(trim(p_category)) returning id into cid; end if; end if;
 insert into public.tbl_chat_rooms(room_type,created_by,title,tagline,description,category_id,tags,rules,image_url,cover_url,visibility,join_type) values('community',me,trim(p_name),nullif(trim(p_tagline),''),coalesce(trim(p_description),''),cid,coalesce(p_tags,'{}'),coalesce(p_rules,'{}'),nullif(p_image_path,''),nullif(p_cover_path,''),p_visibility,case when p_visibility='private' then 'approval' else 'direct' end) returning id into rid;
 insert into public.tbl_chat_participants(room_id,user_id,role) values(rid,me,'admin'); return rid;
end $$;
create or replace function public.community_join(p_room_id integer) returns jsonb language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); jt text; begin select join_type into jt from public.tbl_chat_rooms where id=p_room_id and room_type='community'; if jt is null then raise exception 'Community not found'; end if; if jt='direct' then insert into public.tbl_chat_participants(room_id,user_id,role) values(p_room_id,me,'member') on conflict(room_id,user_id) do nothing; delete from public.tbl_community_join_requests where room_id=p_room_id and user_id=me; return jsonb_build_object('room_id',p_room_id,'role','member','status','active'); else insert into public.tbl_community_join_requests(room_id,user_id,status) values(p_room_id,me,'pending') on conflict do nothing; return jsonb_build_object('room_id',p_room_id,'role','member','status','pending'); end if; end $$;
create or replace function public.community_leave(p_room_id integer) returns void language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); begin if exists(select 1 from public.tbl_chat_rooms where id=p_room_id and created_by=me) then raise exception 'Community owner cannot leave'; end if; delete from public.tbl_chat_participants where room_id=p_room_id and user_id=me; delete from public.tbl_community_join_requests where room_id=p_room_id and user_id=me; end $$;
create or replace function public.community_create_post(p_room_id integer,p_title text,p_body text,p_category text,p_media_path text default null,p_media_type text default null) returns jsonb language plpgsql security definer set search_path=public as $$
declare me integer:=public.get_current_app_user_id(); mid bigint; mtype text:=case when p_media_type in ('image','video') then p_media_type else 'text' end; ctime timestamptz;
begin perform public.assert_chat_membership(p_room_id); if trim(coalesce(p_title,''))='' and trim(coalesce(p_body,''))='' and p_media_path is null then raise exception 'Post is empty'; end if; insert into public.tbl_messages(room_id,sender_id,content,message_type,media_url,is_delivered,client_id) values(p_room_id,me,coalesce(nullif(trim(p_body),''),trim(p_title)),mtype,p_media_path,true,gen_random_uuid()) returning id,created_at into mid,ctime; insert into public.tbl_community_posts(id,room_id,user_id,title,body,media_url,media_type) values(mid,p_room_id,me,nullif(trim(p_title),''),coalesce(p_body,''),p_media_path,p_media_type) on conflict(id) do nothing; return jsonb_build_object('id',mid,'room_id',p_room_id,'community_id',p_room_id,'sender_id',me,'author_id',me,'title',coalesce(p_title,''),'body',coalesce(p_body,''),'content',coalesce(p_body,''),'category',coalesce(p_category,'General'),'media_url',p_media_path,'media_type',p_media_type,'created_at',ctime,'updated_at',ctime); end $$;
create or replace function public.community_set_post_reaction(p_post_id bigint,p_reaction text default null) returns void language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); begin if not exists(select 1 from public.tbl_community_posts p where p.id=p_post_id and public.is_chat_member(p.room_id)) then raise exception 'Post unavailable' using errcode='42501'; end if; delete from public.tbl_community_post_reactions where post_id=p_post_id and user_id=me; if p_reaction is not null then insert into public.tbl_community_post_reactions(post_id,user_id,reaction) values(p_post_id,me,p_reaction); end if; end $$;
create or replace function public.community_list_post_comments(p_post_id bigint,p_page integer default 1,p_page_size integer default 20) returns jsonb language plpgsql stable security definer set search_path=public as $$ declare total integer; items jsonb; begin if not exists(select 1 from public.tbl_community_posts p where p.id=p_post_id and public.is_chat_member(p.room_id)) then raise exception 'Post unavailable' using errcode='42501'; end if; select count(*) into total from public.tbl_community_post_comments where post_id=p_post_id and deleted_at is null; select coalesce(jsonb_agg(x order by (x->>'created_at')::timestamptz),'[]') into items from (select jsonb_build_object('id',c.id,'post_id',c.post_id,'user_id',c.user_id,'author_id',c.user_id,'body',c.body,'parent_id',c.parent_id,'created_at',c.created_at,'updated_at',c.updated_at) x from public.tbl_community_post_comments c where c.post_id=p_post_id and c.deleted_at is null order by c.created_at offset (greatest(p_page,1)-1)*least(greatest(p_page_size,1),50) limit least(greatest(p_page_size,1),50)) q; return jsonb_build_object('items',items,'total',total,'has_more',greatest(p_page,1)*least(greatest(p_page_size,1),50)<total); end $$;
create or replace function public.community_create_post_comment(p_post_id bigint,p_body text,p_parent_id bigint default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); r public.tbl_community_post_comments; begin if length(trim(p_body)) not between 1 and 2000 then raise exception 'Invalid comment'; end if; if not exists(select 1 from public.tbl_community_posts p where p.id=p_post_id and public.is_chat_member(p.room_id)) then raise exception 'Post unavailable' using errcode='42501'; end if; insert into public.tbl_community_post_comments(post_id,user_id,body,parent_id) values(p_post_id,me,trim(p_body),p_parent_id) returning * into r; return to_jsonb(r)||jsonb_build_object('author_id',me); end $$;

create or replace function public.vibe_create(p_event_id bigint,p_media_path text,p_media_type text,p_caption text,p_hashtags text[],p_visibility text) returns jsonb language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); r public.tbl_activity_vibes; mt text:=case when p_media_type='image' then 'photo' else p_media_type end; begin if mt not in ('photo','video') or nullif(p_media_path,'') is null then raise exception 'Invalid vibe media'; end if; if p_visibility not in ('public','activity','private') then raise exception 'Invalid vibe visibility'; end if; insert into public.tbl_activity_vibes(event_id,user_id,media_url,media_type,caption,hashtags,visibility) values(p_event_id,me,p_media_path,mt,left(coalesce(p_caption,''),2200),coalesce(p_hashtags,'{}'),p_visibility) returning * into r; return to_jsonb(r); end $$;
create or replace function public.vibe_delete(p_vibe_id bigint) returns jsonb language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); path text; begin delete from public.tbl_activity_vibes where id=p_vibe_id and user_id=me returning media_url into path; if path is null then raise exception 'Vibe not found' using errcode='42501'; end if; return jsonb_build_object('id',p_vibe_id,'media_path',path); end $$;
create or replace function public.vibe_set_liked(p_vibe_id bigint,p_liked boolean) returns void language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); begin if p_liked then insert into public.tbl_vibe_likes(vibe_id,user_id) values(p_vibe_id,me) on conflict(vibe_id,user_id) do nothing; else delete from public.tbl_vibe_likes where vibe_id=p_vibe_id and user_id=me; end if; update public.tbl_activity_vibes set likes_count=(select count(*) from public.tbl_vibe_likes where vibe_id=p_vibe_id),updated_at=now() where id=p_vibe_id; end $$;
create or replace function public.vibe_create_comment(p_vibe_id bigint,p_body text,p_parent_id integer default null) returns jsonb language plpgsql security definer set search_path=public as $$ declare me integer:=public.get_current_app_user_id(); r public.tbl_vibe_comments; begin if length(trim(p_body)) not between 1 and 2000 then raise exception 'Invalid comment'; end if; insert into public.tbl_vibe_comments(vibe_id,user_id,text,parent_id) values(p_vibe_id,me,trim(p_body),p_parent_id) returning * into r; return to_jsonb(r)||jsonb_build_object('body',r.text,'author_id',me); end $$;
create or replace function public.vibe_delete_comment(p_comment_id integer) returns void language plpgsql security definer set search_path=public as $$ begin delete from public.tbl_vibe_comments where id=p_comment_id and user_id=public.get_current_app_user_id(); end $$;
create or replace function public.vibe_track_share(p_vibe_id bigint,p_channel text) returns jsonb language plpgsql security definer set search_path=public as $$ declare r public.tbl_vibe_shares; begin if p_channel not in ('copy_link','message','external') then raise exception 'Invalid share channel'; end if; insert into public.tbl_vibe_shares(vibe_id,user_id,channel) values(p_vibe_id,public.get_current_app_user_id(),p_channel) returning * into r; return to_jsonb(r); end $$;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('communities','communities',false,20971520,array['image/jpeg','image/png','image/webp','video/mp4']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
alter table public.tbl_vibe_shares enable row level security; revoke all on public.tbl_vibe_shares from anon,authenticated; grant select,insert,delete on public.tbl_vibe_shares to authenticated; create policy wenitro_admin_all on public.tbl_vibe_shares for all to authenticated using(public.is_wenitro_admin()) with check(public.is_wenitro_admin()); create policy own_vibe_shares on public.tbl_vibe_shares for all to authenticated using(user_id=public.current_app_user_id()) with check(user_id=public.current_app_user_id());
create policy community_comments_read on public.tbl_community_post_comments for select to authenticated using(exists(select 1 from public.tbl_community_posts p where p.id=post_id and public.is_chat_member(p.room_id))); create policy own_community_comments on public.tbl_community_post_comments for all to authenticated using(user_id=public.current_app_user_id()) with check(user_id=public.current_app_user_id());
create policy community_reactions_read on public.tbl_community_post_reactions for select to authenticated using(exists(select 1 from public.tbl_community_posts p where p.id=post_id and public.is_chat_member(p.room_id))); create policy own_community_reactions on public.tbl_community_post_reactions for all to authenticated using(user_id=public.current_app_user_id()) with check(user_id=public.current_app_user_id());
drop policy owner_storage_insert on storage.objects; create policy owner_storage_insert on storage.objects for insert to authenticated with check(bucket_id in ('avatars','activity-media','vibes','stories','community','communities','messages','verification') and (storage.foldername(name))[1]=auth.uid()::text);
drop policy private_media_read on storage.objects; create policy private_media_read on storage.objects for select to authenticated using(bucket_id in ('activity-media','vibes','stories','community','communities') or (bucket_id in ('messages','verification') and owner_id=auth.uid()::text));
revoke execute on function public.get_current_legacy_user_id(),public.community_create(text,text,text,text,text[],text[],text,text,text),public.community_join(integer),public.community_leave(integer),public.community_create_post(integer,text,text,text,text,text),public.community_set_post_reaction(bigint,text),public.community_list_post_comments(bigint,integer,integer),public.community_create_post_comment(bigint,text,bigint),public.vibe_create(bigint,text,text,text,text[],text),public.vibe_delete(bigint),public.vibe_set_liked(bigint,boolean),public.vibe_create_comment(bigint,text,integer),public.vibe_delete_comment(integer),public.vibe_track_share(bigint,text) from public,anon;
grant execute on function public.get_current_legacy_user_id(),public.community_create(text,text,text,text,text[],text[],text,text,text),public.community_join(integer),public.community_leave(integer),public.community_create_post(integer,text,text,text,text,text),public.community_set_post_reaction(bigint,text),public.community_list_post_comments(bigint,integer,integer),public.community_create_post_comment(bigint,text,bigint),public.vibe_create(bigint,text,text,text,text[],text),public.vibe_delete(bigint),public.vibe_set_liked(bigint,boolean),public.vibe_create_comment(bigint,text,integer),public.vibe_delete_comment(integer),public.vibe_track_share(bigint,text) to authenticated;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='tbl_vibe_comments') then alter publication supabase_realtime add table public.tbl_vibe_comments; end if; end $$;
